/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.1.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using TemplateFox.SDK.Client;
using TemplateFox.SDK.Api;
// uncomment below to import models
//using TemplateFox.SDK.Model;

namespace TemplateFox.SDK.Test.Api
{
    /// <summary>
    ///  Class for testing IntegrationsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class IntegrationsApiTests : IDisposable
    {
        private IntegrationsApi instance;

        public IntegrationsApiTests()
        {
            instance = new IntegrationsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IntegrationsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' IntegrationsApi
            //Assert.IsType<IntegrationsApi>(instance);
        }

        /// <summary>
        /// Test DeleteS3Config
        /// </summary>
        [Fact]
        public void DeleteS3ConfigTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.DeleteS3Config();
            //Assert.IsType<S3SuccessResponse>(response);
        }

        /// <summary>
        /// Test GetS3Config
        /// </summary>
        [Fact]
        public void GetS3ConfigTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetS3Config();
            //Assert.IsType<S3ConfigResponse>(response);
        }

        /// <summary>
        /// Test SaveS3Config
        /// </summary>
        [Fact]
        public void SaveS3ConfigTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //S3ConfigRequest s3ConfigRequest = null;
            //var response = instance.SaveS3Config(s3ConfigRequest);
            //Assert.IsType<S3SuccessResponse>(response);
        }

        /// <summary>
        /// Test TestS3Connection
        /// </summary>
        [Fact]
        public void TestS3ConnectionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.TestS3Connection();
            //Assert.IsType<S3TestResponse>(response);
        }
    }
}
