/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.1.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using TemplateFox.SDK.Client;
using TemplateFox.SDK.Api;
// uncomment below to import models
//using TemplateFox.SDK.Model;

namespace TemplateFox.SDK.Test.Api
{
    /// <summary>
    ///  Class for testing PDFApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class PDFApiTests : IDisposable
    {
        private PDFApi instance;

        public PDFApiTests()
        {
            instance = new PDFApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PDFApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' PDFApi
            //Assert.IsType<PDFApi>(instance);
        }

        /// <summary>
        /// Test CreatePdf
        /// </summary>
        [Fact]
        public void CreatePdfTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreatePdfRequest createPdfRequest = null;
            //var response = instance.CreatePdf(createPdfRequest);
            //Assert.IsType<CreatePdfResponse>(response);
        }
    }
}
