/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.5.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using TemplateFox.SDK.Client;
using TemplateFox.SDK.Api;
// uncomment below to import models
//using TemplateFox.SDK.Model;

namespace TemplateFox.SDK.Test.Api
{
    /// <summary>
    ///  Class for testing PDFAsyncApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class PDFAsyncApiTests : IDisposable
    {
        private PDFAsyncApi instance;

        public PDFAsyncApiTests()
        {
            instance = new PDFAsyncApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PDFAsyncApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' PDFAsyncApi
            //Assert.IsType<PDFAsyncApi>(instance);
        }

        /// <summary>
        /// Test CreatePdfAsync
        /// </summary>
        [Fact]
        public void CreatePdfAsyncTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateAsyncPdfRequest createAsyncPdfRequest = null;
            //var response = instance.CreatePdfAsync(createAsyncPdfRequest);
            //Assert.IsType<CreateAsyncPdfResponse>(response);
        }

        /// <summary>
        /// Test GetPdfJobStatus
        /// </summary>
        [Fact]
        public void GetPdfJobStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string jobId = null;
            //var response = instance.GetPdfJobStatus(jobId);
            //Assert.IsType<JobStatusResponse>(response);
        }

        /// <summary>
        /// Test ListPdfJobs
        /// </summary>
        [Fact]
        public void ListPdfJobsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? limit = null;
            //int? offset = null;
            //JobStatus? status = null;
            //var response = instance.ListPdfJobs(limit, offset, status);
            //Assert.IsType<JobListResponse>(response);
        }
    }
}
