/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.1.1.dev2+gfe6303fdd.d20260209
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TemplateFox.SDK.Client.FileParameter;
using OpenAPIDateConverter = TemplateFox.SDK.Client.OpenAPIDateConverter;

namespace TemplateFox.SDK.Model
{
    /// <summary>
    /// Response for account info endpoint
    /// </summary>
    [DataContract(Name = "AccountInfoResponse")]
    public partial class AccountInfoResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AccountInfoResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AccountInfoResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AccountInfoResponse" /> class.
        /// </summary>
        /// <param name="credits">Remaining credits (required).</param>
        /// <param name="email">email.</param>
        public AccountInfoResponse(int credits = default, string email = default)
        {
            this.Credits = credits;
            this.Email = email;
        }

        /// <summary>
        /// Remaining credits
        /// </summary>
        /// <value>Remaining credits</value>
        [DataMember(Name = "credits", IsRequired = true, EmitDefaultValue = true)]
        public int Credits { get; set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [DataMember(Name = "email", EmitDefaultValue = true)]
        public string Email { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AccountInfoResponse {\n");
            sb.Append("  Credits: ").Append(Credits).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
