/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.5.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TemplateFox.SDK.Client.FileParameter;
using OpenAPIDateConverter = TemplateFox.SDK.Client.OpenAPIDateConverter;

namespace TemplateFox.SDK.Model
{
    /// <summary>
    /// Request model for async PDF generation
    /// </summary>
    [DataContract(Name = "CreateAsyncPdfRequest")]
    public partial class CreateAsyncPdfRequest : IValidatableObject
    {

        /// <summary>
        /// Export format. Currently only &#x60;url&#x60; is supported for async.
        /// </summary>
        /// <value>Export format. Currently only &#x60;url&#x60; is supported for async.</value>
        [DataMember(Name = "export_type", EmitDefaultValue = false)]
        public AppRoutersV1PdfAsyncExportType? ExportType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateAsyncPdfRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateAsyncPdfRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateAsyncPdfRequest" /> class.
        /// </summary>
        /// <param name="templateId">**Required.** Template short ID (12 characters) (required).</param>
        /// <param name="data">**Required.** Key-value data to render in the template. (required).</param>
        /// <param name="exportType">Export format. Currently only &#x60;url&#x60; is supported for async..</param>
        /// <param name="expiration">URL expiration in seconds (60-604800). Default: 86400 (24 hours). (default to 86400).</param>
        /// <param name="filename">filename.</param>
        /// <param name="storeS3">Upload to your configured S3 bucket instead of CDN. (default to false).</param>
        /// <param name="s3Filepath">s3Filepath.</param>
        /// <param name="s3Bucket">s3Bucket.</param>
        /// <param name="webhookUrl">webhookUrl.</param>
        /// <param name="webhookSecret">webhookSecret.</param>
        public CreateAsyncPdfRequest(string templateId = default, Dictionary<string, Object> data = default, AppRoutersV1PdfAsyncExportType? exportType = default, int expiration = 86400, string filename = default, bool storeS3 = false, string s3Filepath = default, string s3Bucket = default, string webhookUrl = default, string webhookSecret = default)
        {
            // to ensure "templateId" is required (not null)
            if (templateId == null)
            {
                throw new ArgumentNullException("templateId is a required property for CreateAsyncPdfRequest and cannot be null");
            }
            this.TemplateId = templateId;
            // to ensure "data" is required (not null)
            if (data == null)
            {
                throw new ArgumentNullException("data is a required property for CreateAsyncPdfRequest and cannot be null");
            }
            this.Data = data;
            this.ExportType = exportType;
            this.Expiration = expiration;
            this.Filename = filename;
            this.StoreS3 = storeS3;
            this.S3Filepath = s3Filepath;
            this.S3Bucket = s3Bucket;
            this.WebhookUrl = webhookUrl;
            this.WebhookSecret = webhookSecret;
        }

        /// <summary>
        /// **Required.** Template short ID (12 characters)
        /// </summary>
        /// <value>**Required.** Template short ID (12 characters)</value>
        [DataMember(Name = "template_id", IsRequired = true, EmitDefaultValue = true)]
        public string TemplateId { get; set; }

        /// <summary>
        /// **Required.** Key-value data to render in the template.
        /// </summary>
        /// <value>**Required.** Key-value data to render in the template.</value>
        [DataMember(Name = "data", IsRequired = true, EmitDefaultValue = true)]
        public Dictionary<string, Object> Data { get; set; }

        /// <summary>
        /// URL expiration in seconds (60-604800). Default: 86400 (24 hours).
        /// </summary>
        /// <value>URL expiration in seconds (60-604800). Default: 86400 (24 hours).</value>
        [DataMember(Name = "expiration", EmitDefaultValue = false)]
        public int Expiration { get; set; }

        /// <summary>
        /// Gets or Sets Filename
        /// </summary>
        [DataMember(Name = "filename", EmitDefaultValue = true)]
        public string Filename { get; set; }

        /// <summary>
        /// Upload to your configured S3 bucket instead of CDN.
        /// </summary>
        /// <value>Upload to your configured S3 bucket instead of CDN.</value>
        [DataMember(Name = "store_s3", EmitDefaultValue = true)]
        public bool StoreS3 { get; set; }

        /// <summary>
        /// Gets or Sets S3Filepath
        /// </summary>
        [DataMember(Name = "s3_filepath", EmitDefaultValue = true)]
        public string S3Filepath { get; set; }

        /// <summary>
        /// Gets or Sets S3Bucket
        /// </summary>
        [DataMember(Name = "s3_bucket", EmitDefaultValue = true)]
        public string S3Bucket { get; set; }

        /// <summary>
        /// Gets or Sets WebhookUrl
        /// </summary>
        [DataMember(Name = "webhook_url", EmitDefaultValue = true)]
        public string WebhookUrl { get; set; }

        /// <summary>
        /// Gets or Sets WebhookSecret
        /// </summary>
        [DataMember(Name = "webhook_secret", EmitDefaultValue = true)]
        public string WebhookSecret { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateAsyncPdfRequest {\n");
            sb.Append("  TemplateId: ").Append(TemplateId).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  ExportType: ").Append(ExportType).Append("\n");
            sb.Append("  Expiration: ").Append(Expiration).Append("\n");
            sb.Append("  Filename: ").Append(Filename).Append("\n");
            sb.Append("  StoreS3: ").Append(StoreS3).Append("\n");
            sb.Append("  S3Filepath: ").Append(S3Filepath).Append("\n");
            sb.Append("  S3Bucket: ").Append(S3Bucket).Append("\n");
            sb.Append("  WebhookUrl: ").Append(WebhookUrl).Append("\n");
            sb.Append("  WebhookSecret: ").Append(WebhookSecret).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // TemplateId (string) maxLength
            if (this.TemplateId != null && this.TemplateId.Length > 12)
            {
                yield return new ValidationResult("Invalid value for TemplateId, length must be less than 12.", new [] { "TemplateId" });
            }

            // TemplateId (string) minLength
            if (this.TemplateId != null && this.TemplateId.Length < 12)
            {
                yield return new ValidationResult("Invalid value for TemplateId, length must be greater than 12.", new [] { "TemplateId" });
            }

            // Expiration (int) maximum
            if (this.Expiration > (int)604800)
            {
                yield return new ValidationResult("Invalid value for Expiration, must be a value less than or equal to 604800.", new [] { "Expiration" });
            }

            // Expiration (int) minimum
            if (this.Expiration < (int)60)
            {
                yield return new ValidationResult("Invalid value for Expiration, must be a value greater than or equal to 60.", new [] { "Expiration" });
            }

            // Filename (string) maxLength
            if (this.Filename != null && this.Filename.Length > 100)
            {
                yield return new ValidationResult("Invalid value for Filename, length must be less than 100.", new [] { "Filename" });
            }

            if (this.Filename != null) {
                // Filename (string) pattern
                Regex regexFilename = new Regex(@"^[a-zA-Z0-9_\-\.]+$", RegexOptions.CultureInvariant);
                if (!regexFilename.Match(this.Filename).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Filename, must match a pattern of " + regexFilename, new [] { "Filename" });
                }
            }

            // S3Filepath (string) maxLength
            if (this.S3Filepath != null && this.S3Filepath.Length > 500)
            {
                yield return new ValidationResult("Invalid value for S3Filepath, length must be less than 500.", new [] { "S3Filepath" });
            }

            if (this.S3Filepath != null) {
                // S3Filepath (string) pattern
                Regex regexS3Filepath = new Regex(@"^[a-zA-Z0-9_\-\./]+$", RegexOptions.CultureInvariant);
                if (!regexS3Filepath.Match(this.S3Filepath).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for S3Filepath, must match a pattern of " + regexS3Filepath, new [] { "S3Filepath" });
                }
            }

            // S3Bucket (string) maxLength
            if (this.S3Bucket != null && this.S3Bucket.Length > 63)
            {
                yield return new ValidationResult("Invalid value for S3Bucket, length must be less than 63.", new [] { "S3Bucket" });
            }

            // S3Bucket (string) minLength
            if (this.S3Bucket != null && this.S3Bucket.Length < 3)
            {
                yield return new ValidationResult("Invalid value for S3Bucket, length must be greater than 3.", new [] { "S3Bucket" });
            }

            if (this.S3Bucket != null) {
                // S3Bucket (string) pattern
                Regex regexS3Bucket = new Regex(@"^[a-z0-9][a-z0-9.\-]*[a-z0-9]$", RegexOptions.CultureInvariant);
                if (!regexS3Bucket.Match(this.S3Bucket).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for S3Bucket, must match a pattern of " + regexS3Bucket, new [] { "S3Bucket" });
                }
            }

            // WebhookUrl (string) maxLength
            if (this.WebhookUrl != null && this.WebhookUrl.Length > 2083)
            {
                yield return new ValidationResult("Invalid value for WebhookUrl, length must be less than 2083.", new [] { "WebhookUrl" });
            }

            // WebhookUrl (string) minLength
            if (this.WebhookUrl != null && this.WebhookUrl.Length < 1)
            {
                yield return new ValidationResult("Invalid value for WebhookUrl, length must be greater than 1.", new [] { "WebhookUrl" });
            }

            // WebhookSecret (string) maxLength
            if (this.WebhookSecret != null && this.WebhookSecret.Length > 256)
            {
                yield return new ValidationResult("Invalid value for WebhookSecret, length must be less than 256.", new [] { "WebhookSecret" });
            }

            // WebhookSecret (string) minLength
            if (this.WebhookSecret != null && this.WebhookSecret.Length < 16)
            {
                yield return new ValidationResult("Invalid value for WebhookSecret, length must be greater than 16.", new [] { "WebhookSecret" });
            }

            yield break;
        }
    }

}
