/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.6.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TemplateFox.SDK.Client.FileParameter;
using OpenAPIDateConverter = TemplateFox.SDK.Client.OpenAPIDateConverter;

namespace TemplateFox.SDK.Model
{
    /// <summary>
    /// Response for async PDF creation
    /// </summary>
    [DataContract(Name = "CreateAsyncPdfResponse")]
    public partial class CreateAsyncPdfResponse : IValidatableObject
    {

        /// <summary>
        /// Initial job status (always &#39;pending&#39;)
        /// </summary>
        /// <value>Initial job status (always &#39;pending&#39;)</value>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public JobStatus Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateAsyncPdfResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateAsyncPdfResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateAsyncPdfResponse" /> class.
        /// </summary>
        /// <param name="jobId">Unique job identifier for status polling (required).</param>
        /// <param name="status">Initial job status (always &#39;pending&#39;) (required).</param>
        /// <param name="creditsRemaining">Remaining credits after this request (required).</param>
        public CreateAsyncPdfResponse(string jobId = default, JobStatus status = default, int creditsRemaining = default)
        {
            // to ensure "jobId" is required (not null)
            if (jobId == null)
            {
                throw new ArgumentNullException("jobId is a required property for CreateAsyncPdfResponse and cannot be null");
            }
            this.JobId = jobId;
            this.Status = status;
            this.CreditsRemaining = creditsRemaining;
        }

        /// <summary>
        /// Unique job identifier for status polling
        /// </summary>
        /// <value>Unique job identifier for status polling</value>
        [DataMember(Name = "job_id", IsRequired = true, EmitDefaultValue = true)]
        public string JobId { get; set; }

        /// <summary>
        /// Remaining credits after this request
        /// </summary>
        /// <value>Remaining credits after this request</value>
        [DataMember(Name = "credits_remaining", IsRequired = true, EmitDefaultValue = true)]
        public int CreditsRemaining { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateAsyncPdfResponse {\n");
            sb.Append("  JobId: ").Append(JobId).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  CreditsRemaining: ").Append(CreditsRemaining).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
