/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.5.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TemplateFox.SDK.Client.FileParameter;
using OpenAPIDateConverter = TemplateFox.SDK.Client.OpenAPIDateConverter;

namespace TemplateFox.SDK.Model
{
    /// <summary>
    /// Response for job list query
    /// </summary>
    [DataContract(Name = "JobListResponse")]
    public partial class JobListResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JobListResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected JobListResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="JobListResponse" /> class.
        /// </summary>
        /// <param name="jobs">List of jobs (required).</param>
        /// <param name="total">Total number of jobs matching filter (required).</param>
        /// <param name="limit">Page size (required).</param>
        /// <param name="offset">Page offset (required).</param>
        public JobListResponse(List<JobStatusResponse> jobs = default, int total = default, int limit = default, int offset = default)
        {
            // to ensure "jobs" is required (not null)
            if (jobs == null)
            {
                throw new ArgumentNullException("jobs is a required property for JobListResponse and cannot be null");
            }
            this.Jobs = jobs;
            this.Total = total;
            this.Limit = limit;
            this.Offset = offset;
        }

        /// <summary>
        /// List of jobs
        /// </summary>
        /// <value>List of jobs</value>
        [DataMember(Name = "jobs", IsRequired = true, EmitDefaultValue = true)]
        public List<JobStatusResponse> Jobs { get; set; }

        /// <summary>
        /// Total number of jobs matching filter
        /// </summary>
        /// <value>Total number of jobs matching filter</value>
        [DataMember(Name = "total", IsRequired = true, EmitDefaultValue = true)]
        public int Total { get; set; }

        /// <summary>
        /// Page size
        /// </summary>
        /// <value>Page size</value>
        [DataMember(Name = "limit", IsRequired = true, EmitDefaultValue = true)]
        public int Limit { get; set; }

        /// <summary>
        /// Page offset
        /// </summary>
        /// <value>Page offset</value>
        [DataMember(Name = "offset", IsRequired = true, EmitDefaultValue = true)]
        public int Offset { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class JobListResponse {\n");
            sb.Append("  Jobs: ").Append(Jobs).Append("\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("  Limit: ").Append(Limit).Append("\n");
            sb.Append("  Offset: ").Append(Offset).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
