/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TemplateFox.SDK.Client.FileParameter;
using OpenAPIDateConverter = TemplateFox.SDK.Client.OpenAPIDateConverter;

namespace TemplateFox.SDK.Model
{
    /// <summary>
    /// Response for job status query
    /// </summary>
    [DataContract(Name = "JobStatusResponse")]
    public partial class JobStatusResponse : IValidatableObject
    {

        /// <summary>
        /// Current job status
        /// </summary>
        /// <value>Current job status</value>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public JobStatus Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="JobStatusResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected JobStatusResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="JobStatusResponse" /> class.
        /// </summary>
        /// <param name="id">Job ID (required).</param>
        /// <param name="status">Current job status (required).</param>
        /// <param name="templateId">Template used for generation (required).</param>
        /// <param name="exportType">Export type (url) (required).</param>
        /// <param name="filename">filename.</param>
        /// <param name="storeS3">Whether S3 storage was requested (required).</param>
        /// <param name="createdAt">Job creation timestamp (ISO 8601) (required).</param>
        /// <param name="updatedAt">Last update timestamp (ISO 8601) (required).</param>
        /// <param name="completedAt">completedAt.</param>
        /// <param name="resultUrl">resultUrl.</param>
        /// <param name="resultFilename">resultFilename.</param>
        /// <param name="resultExpiresAt">resultExpiresAt.</param>
        /// <param name="resultS3Bucket">resultS3Bucket.</param>
        /// <param name="resultS3Key">resultS3Key.</param>
        /// <param name="errorMessage">errorMessage.</param>
        /// <param name="errorCode">errorCode.</param>
        public JobStatusResponse(string id = default, JobStatus status = default, string templateId = default, string exportType = default, string filename = default, bool storeS3 = default, string createdAt = default, string updatedAt = default, string completedAt = default, string resultUrl = default, string resultFilename = default, string resultExpiresAt = default, string resultS3Bucket = default, string resultS3Key = default, string errorMessage = default, string errorCode = default)
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for JobStatusResponse and cannot be null");
            }
            this.Id = id;
            this.Status = status;
            // to ensure "templateId" is required (not null)
            if (templateId == null)
            {
                throw new ArgumentNullException("templateId is a required property for JobStatusResponse and cannot be null");
            }
            this.TemplateId = templateId;
            // to ensure "exportType" is required (not null)
            if (exportType == null)
            {
                throw new ArgumentNullException("exportType is a required property for JobStatusResponse and cannot be null");
            }
            this.ExportType = exportType;
            this.StoreS3 = storeS3;
            // to ensure "createdAt" is required (not null)
            if (createdAt == null)
            {
                throw new ArgumentNullException("createdAt is a required property for JobStatusResponse and cannot be null");
            }
            this.CreatedAt = createdAt;
            // to ensure "updatedAt" is required (not null)
            if (updatedAt == null)
            {
                throw new ArgumentNullException("updatedAt is a required property for JobStatusResponse and cannot be null");
            }
            this.UpdatedAt = updatedAt;
            this.Filename = filename;
            this.CompletedAt = completedAt;
            this.ResultUrl = resultUrl;
            this.ResultFilename = resultFilename;
            this.ResultExpiresAt = resultExpiresAt;
            this.ResultS3Bucket = resultS3Bucket;
            this.ResultS3Key = resultS3Key;
            this.ErrorMessage = errorMessage;
            this.ErrorCode = errorCode;
        }

        /// <summary>
        /// Job ID
        /// </summary>
        /// <value>Job ID</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Template used for generation
        /// </summary>
        /// <value>Template used for generation</value>
        [DataMember(Name = "template_id", IsRequired = true, EmitDefaultValue = true)]
        public string TemplateId { get; set; }

        /// <summary>
        /// Export type (url)
        /// </summary>
        /// <value>Export type (url)</value>
        [DataMember(Name = "export_type", IsRequired = true, EmitDefaultValue = true)]
        public string ExportType { get; set; }

        /// <summary>
        /// Gets or Sets Filename
        /// </summary>
        [DataMember(Name = "filename", EmitDefaultValue = true)]
        public string Filename { get; set; }

        /// <summary>
        /// Whether S3 storage was requested
        /// </summary>
        /// <value>Whether S3 storage was requested</value>
        [DataMember(Name = "store_s3", IsRequired = true, EmitDefaultValue = true)]
        public bool StoreS3 { get; set; }

        /// <summary>
        /// Job creation timestamp (ISO 8601)
        /// </summary>
        /// <value>Job creation timestamp (ISO 8601)</value>
        [DataMember(Name = "created_at", IsRequired = true, EmitDefaultValue = true)]
        public string CreatedAt { get; set; }

        /// <summary>
        /// Last update timestamp (ISO 8601)
        /// </summary>
        /// <value>Last update timestamp (ISO 8601)</value>
        [DataMember(Name = "updated_at", IsRequired = true, EmitDefaultValue = true)]
        public string UpdatedAt { get; set; }

        /// <summary>
        /// Gets or Sets CompletedAt
        /// </summary>
        [DataMember(Name = "completed_at", EmitDefaultValue = true)]
        public string CompletedAt { get; set; }

        /// <summary>
        /// Gets or Sets ResultUrl
        /// </summary>
        [DataMember(Name = "result_url", EmitDefaultValue = true)]
        public string ResultUrl { get; set; }

        /// <summary>
        /// Gets or Sets ResultFilename
        /// </summary>
        [DataMember(Name = "result_filename", EmitDefaultValue = true)]
        public string ResultFilename { get; set; }

        /// <summary>
        /// Gets or Sets ResultExpiresAt
        /// </summary>
        [DataMember(Name = "result_expires_at", EmitDefaultValue = true)]
        public string ResultExpiresAt { get; set; }

        /// <summary>
        /// Gets or Sets ResultS3Bucket
        /// </summary>
        [DataMember(Name = "result_s3_bucket", EmitDefaultValue = true)]
        public string ResultS3Bucket { get; set; }

        /// <summary>
        /// Gets or Sets ResultS3Key
        /// </summary>
        [DataMember(Name = "result_s3_key", EmitDefaultValue = true)]
        public string ResultS3Key { get; set; }

        /// <summary>
        /// Gets or Sets ErrorMessage
        /// </summary>
        [DataMember(Name = "error_message", EmitDefaultValue = true)]
        public string ErrorMessage { get; set; }

        /// <summary>
        /// Gets or Sets ErrorCode
        /// </summary>
        [DataMember(Name = "error_code", EmitDefaultValue = true)]
        public string ErrorCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class JobStatusResponse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  TemplateId: ").Append(TemplateId).Append("\n");
            sb.Append("  ExportType: ").Append(ExportType).Append("\n");
            sb.Append("  Filename: ").Append(Filename).Append("\n");
            sb.Append("  StoreS3: ").Append(StoreS3).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  CompletedAt: ").Append(CompletedAt).Append("\n");
            sb.Append("  ResultUrl: ").Append(ResultUrl).Append("\n");
            sb.Append("  ResultFilename: ").Append(ResultFilename).Append("\n");
            sb.Append("  ResultExpiresAt: ").Append(ResultExpiresAt).Append("\n");
            sb.Append("  ResultS3Bucket: ").Append(ResultS3Bucket).Append("\n");
            sb.Append("  ResultS3Key: ").Append(ResultS3Key).Append("\n");
            sb.Append("  ErrorMessage: ").Append(ErrorMessage).Append("\n");
            sb.Append("  ErrorCode: ").Append(ErrorCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
