/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.4.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TemplateFox.SDK.Client.FileParameter;
using OpenAPIDateConverter = TemplateFox.SDK.Client.OpenAPIDateConverter;

namespace TemplateFox.SDK.Model
{
    /// <summary>
    /// Response for S3 configuration (with masked secret)
    /// </summary>
    [DataContract(Name = "S3ConfigResponse")]
    public partial class S3ConfigResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="S3ConfigResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected S3ConfigResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="S3ConfigResponse" /> class.
        /// </summary>
        /// <param name="configured">Whether S3 is configured (required).</param>
        /// <param name="endpointUrl">S3-compatible endpoint URL (required).</param>
        /// <param name="accessKeyId">Access key ID (required).</param>
        /// <param name="secretAccessKeyMasked">Masked secret access key (shows first 4 and last 4 characters) (required).</param>
        /// <param name="bucketName">S3 bucket name (required).</param>
        /// <param name="defaultPrefix">Default path prefix for uploads (required).</param>
        public S3ConfigResponse(bool configured = default, string endpointUrl = default, string accessKeyId = default, string secretAccessKeyMasked = default, string bucketName = default, string defaultPrefix = default)
        {
            this.Configured = configured;
            // to ensure "endpointUrl" is required (not null)
            if (endpointUrl == null)
            {
                throw new ArgumentNullException("endpointUrl is a required property for S3ConfigResponse and cannot be null");
            }
            this.EndpointUrl = endpointUrl;
            // to ensure "accessKeyId" is required (not null)
            if (accessKeyId == null)
            {
                throw new ArgumentNullException("accessKeyId is a required property for S3ConfigResponse and cannot be null");
            }
            this.AccessKeyId = accessKeyId;
            // to ensure "secretAccessKeyMasked" is required (not null)
            if (secretAccessKeyMasked == null)
            {
                throw new ArgumentNullException("secretAccessKeyMasked is a required property for S3ConfigResponse and cannot be null");
            }
            this.SecretAccessKeyMasked = secretAccessKeyMasked;
            // to ensure "bucketName" is required (not null)
            if (bucketName == null)
            {
                throw new ArgumentNullException("bucketName is a required property for S3ConfigResponse and cannot be null");
            }
            this.BucketName = bucketName;
            // to ensure "defaultPrefix" is required (not null)
            if (defaultPrefix == null)
            {
                throw new ArgumentNullException("defaultPrefix is a required property for S3ConfigResponse and cannot be null");
            }
            this.DefaultPrefix = defaultPrefix;
        }

        /// <summary>
        /// Whether S3 is configured
        /// </summary>
        /// <value>Whether S3 is configured</value>
        [DataMember(Name = "configured", IsRequired = true, EmitDefaultValue = true)]
        public bool Configured { get; set; }

        /// <summary>
        /// S3-compatible endpoint URL
        /// </summary>
        /// <value>S3-compatible endpoint URL</value>
        [DataMember(Name = "endpoint_url", IsRequired = true, EmitDefaultValue = true)]
        public string EndpointUrl { get; set; }

        /// <summary>
        /// Access key ID
        /// </summary>
        /// <value>Access key ID</value>
        [DataMember(Name = "access_key_id", IsRequired = true, EmitDefaultValue = true)]
        public string AccessKeyId { get; set; }

        /// <summary>
        /// Masked secret access key (shows first 4 and last 4 characters)
        /// </summary>
        /// <value>Masked secret access key (shows first 4 and last 4 characters)</value>
        [DataMember(Name = "secret_access_key_masked", IsRequired = true, EmitDefaultValue = true)]
        public string SecretAccessKeyMasked { get; set; }

        /// <summary>
        /// S3 bucket name
        /// </summary>
        /// <value>S3 bucket name</value>
        [DataMember(Name = "bucket_name", IsRequired = true, EmitDefaultValue = true)]
        public string BucketName { get; set; }

        /// <summary>
        /// Default path prefix for uploads
        /// </summary>
        /// <value>Default path prefix for uploads</value>
        [DataMember(Name = "default_prefix", IsRequired = true, EmitDefaultValue = true)]
        public string DefaultPrefix { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class S3ConfigResponse {\n");
            sb.Append("  Configured: ").Append(Configured).Append("\n");
            sb.Append("  EndpointUrl: ").Append(EndpointUrl).Append("\n");
            sb.Append("  AccessKeyId: ").Append(AccessKeyId).Append("\n");
            sb.Append("  SecretAccessKeyMasked: ").Append(SecretAccessKeyMasked).Append("\n");
            sb.Append("  BucketName: ").Append(BucketName).Append("\n");
            sb.Append("  DefaultPrefix: ").Append(DefaultPrefix).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
