/*
 * TemplateFox API
 *
 * Generate PDFs from HTML templates via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TemplateFox.SDK.Client.FileParameter;
using OpenAPIDateConverter = TemplateFox.SDK.Client.OpenAPIDateConverter;

namespace TemplateFox.SDK.Model
{
    /// <summary>
    /// Request model for S3 configuration
    /// </summary>
    [DataContract(Name = "S3ConfigRequest")]
    public partial class S3ConfigRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="S3ConfigRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected S3ConfigRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="S3ConfigRequest" /> class.
        /// </summary>
        /// <param name="endpointUrl">S3-compatible endpoint URL. Must start with https:// (required).</param>
        /// <param name="accessKeyId">Access key ID for S3 authentication (required).</param>
        /// <param name="secretAccessKey">secretAccessKey.</param>
        /// <param name="bucketName">S3 bucket name. Must follow S3 naming conventions (lowercase, no underscores) (required).</param>
        /// <param name="defaultPrefix">Default path prefix for uploaded files. Can include slashes for folder structure (default to &quot;&quot;).</param>
        public S3ConfigRequest(string endpointUrl = default, string accessKeyId = default, string secretAccessKey = default, string bucketName = default, string defaultPrefix = @"")
        {
            // to ensure "endpointUrl" is required (not null)
            if (endpointUrl == null)
            {
                throw new ArgumentNullException("endpointUrl is a required property for S3ConfigRequest and cannot be null");
            }
            this.EndpointUrl = endpointUrl;
            // to ensure "accessKeyId" is required (not null)
            if (accessKeyId == null)
            {
                throw new ArgumentNullException("accessKeyId is a required property for S3ConfigRequest and cannot be null");
            }
            this.AccessKeyId = accessKeyId;
            // to ensure "bucketName" is required (not null)
            if (bucketName == null)
            {
                throw new ArgumentNullException("bucketName is a required property for S3ConfigRequest and cannot be null");
            }
            this.BucketName = bucketName;
            this.SecretAccessKey = secretAccessKey;
            // use default value if no "defaultPrefix" provided
            this.DefaultPrefix = defaultPrefix ?? @"";
        }

        /// <summary>
        /// S3-compatible endpoint URL. Must start with https://
        /// </summary>
        /// <value>S3-compatible endpoint URL. Must start with https://</value>
        [DataMember(Name = "endpoint_url", IsRequired = true, EmitDefaultValue = true)]
        public string EndpointUrl { get; set; }

        /// <summary>
        /// Access key ID for S3 authentication
        /// </summary>
        /// <value>Access key ID for S3 authentication</value>
        [DataMember(Name = "access_key_id", IsRequired = true, EmitDefaultValue = true)]
        public string AccessKeyId { get; set; }

        /// <summary>
        /// Gets or Sets SecretAccessKey
        /// </summary>
        [DataMember(Name = "secret_access_key", EmitDefaultValue = true)]
        public string SecretAccessKey { get; set; }

        /// <summary>
        /// S3 bucket name. Must follow S3 naming conventions (lowercase, no underscores)
        /// </summary>
        /// <value>S3 bucket name. Must follow S3 naming conventions (lowercase, no underscores)</value>
        [DataMember(Name = "bucket_name", IsRequired = true, EmitDefaultValue = true)]
        public string BucketName { get; set; }

        /// <summary>
        /// Default path prefix for uploaded files. Can include slashes for folder structure
        /// </summary>
        /// <value>Default path prefix for uploaded files. Can include slashes for folder structure</value>
        [DataMember(Name = "default_prefix", EmitDefaultValue = false)]
        public string DefaultPrefix { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class S3ConfigRequest {\n");
            sb.Append("  EndpointUrl: ").Append(EndpointUrl).Append("\n");
            sb.Append("  AccessKeyId: ").Append(AccessKeyId).Append("\n");
            sb.Append("  SecretAccessKey: ").Append(SecretAccessKey).Append("\n");
            sb.Append("  BucketName: ").Append(BucketName).Append("\n");
            sb.Append("  DefaultPrefix: ").Append(DefaultPrefix).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // EndpointUrl (string) maxLength
            if (this.EndpointUrl != null && this.EndpointUrl.Length > 200)
            {
                yield return new ValidationResult("Invalid value for EndpointUrl, length must be less than 200.", new [] { "EndpointUrl" });
            }

            // EndpointUrl (string) minLength
            if (this.EndpointUrl != null && this.EndpointUrl.Length < 10)
            {
                yield return new ValidationResult("Invalid value for EndpointUrl, length must be greater than 10.", new [] { "EndpointUrl" });
            }

            if (this.EndpointUrl != null) {
                // EndpointUrl (string) pattern
                Regex regexEndpointUrl = new Regex(@"^https://", RegexOptions.CultureInvariant);
                if (!regexEndpointUrl.Match(this.EndpointUrl).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for EndpointUrl, must match a pattern of " + regexEndpointUrl, new [] { "EndpointUrl" });
                }
            }

            // AccessKeyId (string) maxLength
            if (this.AccessKeyId != null && this.AccessKeyId.Length > 128)
            {
                yield return new ValidationResult("Invalid value for AccessKeyId, length must be less than 128.", new [] { "AccessKeyId" });
            }

            // AccessKeyId (string) minLength
            if (this.AccessKeyId != null && this.AccessKeyId.Length < 16)
            {
                yield return new ValidationResult("Invalid value for AccessKeyId, length must be greater than 16.", new [] { "AccessKeyId" });
            }

            // SecretAccessKey (string) maxLength
            if (this.SecretAccessKey != null && this.SecretAccessKey.Length > 128)
            {
                yield return new ValidationResult("Invalid value for SecretAccessKey, length must be less than 128.", new [] { "SecretAccessKey" });
            }

            // SecretAccessKey (string) minLength
            if (this.SecretAccessKey != null && this.SecretAccessKey.Length < 16)
            {
                yield return new ValidationResult("Invalid value for SecretAccessKey, length must be greater than 16.", new [] { "SecretAccessKey" });
            }

            // BucketName (string) maxLength
            if (this.BucketName != null && this.BucketName.Length > 63)
            {
                yield return new ValidationResult("Invalid value for BucketName, length must be less than 63.", new [] { "BucketName" });
            }

            // BucketName (string) minLength
            if (this.BucketName != null && this.BucketName.Length < 3)
            {
                yield return new ValidationResult("Invalid value for BucketName, length must be greater than 3.", new [] { "BucketName" });
            }

            if (this.BucketName != null) {
                // BucketName (string) pattern
                Regex regexBucketName = new Regex(@"^[a-z0-9][a-z0-9.\-]*[a-z0-9]$", RegexOptions.CultureInvariant);
                if (!regexBucketName.Match(this.BucketName).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for BucketName, must match a pattern of " + regexBucketName, new [] { "BucketName" });
                }
            }

            // DefaultPrefix (string) maxLength
            if (this.DefaultPrefix != null && this.DefaultPrefix.Length > 500)
            {
                yield return new ValidationResult("Invalid value for DefaultPrefix, length must be less than 500.", new [] { "DefaultPrefix" });
            }

            if (this.DefaultPrefix != null) {
                // DefaultPrefix (string) pattern
                Regex regexDefaultPrefix = new Regex(@"^[a-zA-Z0-9_\-\./]*$", RegexOptions.CultureInvariant);
                if (!regexDefaultPrefix.Match(this.DefaultPrefix).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for DefaultPrefix, must match a pattern of " + regexDefaultPrefix, new [] { "DefaultPrefix" });
                }
            }

            yield break;
        }
    }

}
