/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.5.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TemplateFox.SDK.Client.FileParameter;
using OpenAPIDateConverter = TemplateFox.SDK.Client.OpenAPIDateConverter;

namespace TemplateFox.SDK.Model
{
    /// <summary>
    /// Response for S3 connection test
    /// </summary>
    [DataContract(Name = "S3TestResponse")]
    public partial class S3TestResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="S3TestResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected S3TestResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="S3TestResponse" /> class.
        /// </summary>
        /// <param name="success">Whether the connection test succeeded (required).</param>
        /// <param name="message">Test result message (required).</param>
        public S3TestResponse(bool success = default, string message = default)
        {
            this.Success = success;
            // to ensure "message" is required (not null)
            if (message == null)
            {
                throw new ArgumentNullException("message is a required property for S3TestResponse and cannot be null");
            }
            this.Message = message;
        }

        /// <summary>
        /// Whether the connection test succeeded
        /// </summary>
        /// <value>Whether the connection test succeeded</value>
        [DataMember(Name = "success", IsRequired = true, EmitDefaultValue = true)]
        public bool Success { get; set; }

        /// <summary>
        /// Test result message
        /// </summary>
        /// <value>Test result message</value>
        [DataMember(Name = "message", IsRequired = true, EmitDefaultValue = true)]
        public string Message { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class S3TestResponse {\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
