/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TemplateFox.SDK.Client.FileParameter;
using OpenAPIDateConverter = TemplateFox.SDK.Client.OpenAPIDateConverter;
using System.Reflection;

namespace TemplateFox.SDK.Model
{
    /// <summary>
    /// For array fields: spec defining the structure of each item
    /// </summary>
    [JsonConverter(typeof(SpecJsonConverter))]
    [DataContract(Name = "Spec")]
    public partial class Spec : AbstractOpenAPISchema, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Spec" /> class.
        /// </summary>
        public Spec()
        {
            IsNullable = true;
            SchemaType= "anyOf";
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Spec" /> class
        /// with the <see cref="List{TemplateFieldSpec}" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of List&lt;TemplateFieldSpec&gt;.</param>
        public Spec(List<TemplateFieldSpec> actualInstance)
        {
            IsNullable = true;
            SchemaType= "anyOf";
            ActualInstance = actualInstance;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Spec" /> class
        /// with the <see cref="TemplateFieldSpec" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of TemplateFieldSpec.</param>
        public Spec(TemplateFieldSpec actualInstance)
        {
            IsNullable = true;
            SchemaType= "anyOf";
            ActualInstance = actualInstance;
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(List<TemplateFieldSpec>))
                {
                    _actualInstance = value;
                }
                else if (value.GetType() == typeof(TemplateFieldSpec))
                {
                    _actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: List<TemplateFieldSpec>, TemplateFieldSpec");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `List&lt;TemplateFieldSpec&gt;`. If the actual instance is not `List&lt;TemplateFieldSpec&gt;`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of List&lt;TemplateFieldSpec&gt;</returns>
        public List<TemplateFieldSpec> GetList()
        {
            return (List<TemplateFieldSpec>)ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `TemplateFieldSpec`. If the actual instance is not `TemplateFieldSpec`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of TemplateFieldSpec</returns>
        public TemplateFieldSpec GetTemplateFieldSpec()
        {
            return (TemplateFieldSpec)ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Spec {\n");
            sb.Append("  ActualInstance: ").Append(ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(ActualInstance, Spec.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of Spec
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of Spec</returns>
        public static Spec FromJson(string jsonString)
        {
            Spec newSpec = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newSpec;
            }

            try
            {
                newSpec = new Spec(JsonConvert.DeserializeObject<List<TemplateFieldSpec>>(jsonString, Spec.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newSpec;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into List<TemplateFieldSpec>: {1}", jsonString, exception.ToString()));
            }

            try
            {
                newSpec = new Spec(JsonConvert.DeserializeObject<TemplateFieldSpec>(jsonString, Spec.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newSpec;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into TemplateFieldSpec: {1}", jsonString, exception.ToString()));
            }

            // no match found, throw an exception
            throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for Spec
    /// </summary>
    public class SpecJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(Spec).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return Spec.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return Spec.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
