/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TemplateFox.SDK.Client.FileParameter;
using OpenAPIDateConverter = TemplateFox.SDK.Client.OpenAPIDateConverter;

namespace TemplateFox.SDK.Model
{
    /// <summary>
    /// Spec for array item fields
    /// </summary>
    [DataContract(Name = "TemplateFieldSpec")]
    public partial class TemplateFieldSpec : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TemplateFieldSpec" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TemplateFieldSpec() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TemplateFieldSpec" /> class.
        /// </summary>
        /// <param name="name">Field name (required).</param>
        /// <param name="label">Field label (required).</param>
        /// <param name="type">Field type: text, number (default to &quot;text&quot;).</param>
        public TemplateFieldSpec(string name = default, string label = default, string type = @"text")
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for TemplateFieldSpec and cannot be null");
            }
            this.Name = name;
            // to ensure "label" is required (not null)
            if (label == null)
            {
                throw new ArgumentNullException("label is a required property for TemplateFieldSpec and cannot be null");
            }
            this.Label = label;
            // use default value if no "type" provided
            this.Type = type ?? @"text";
        }

        /// <summary>
        /// Field name
        /// </summary>
        /// <value>Field name</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Field label
        /// </summary>
        /// <value>Field label</value>
        [DataMember(Name = "label", IsRequired = true, EmitDefaultValue = true)]
        public string Label { get; set; }

        /// <summary>
        /// Field type: text, number
        /// </summary>
        /// <value>Field type: text, number</value>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public string Type { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TemplateFieldSpec {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Label: ").Append(Label).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
