/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.4.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TemplateFox.SDK.Client.FileParameter;
using OpenAPIDateConverter = TemplateFox.SDK.Client.OpenAPIDateConverter;

namespace TemplateFox.SDK.Model
{
    /// <summary>
    /// Field definition for template variables (compatible with Zapier and Make.com)
    /// </summary>
    [DataContract(Name = "TemplateField")]
    public partial class TemplateField : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TemplateField" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TemplateField() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TemplateField" /> class.
        /// </summary>
        /// <param name="key">Field key/identifier (required).</param>
        /// <param name="label">Human-readable label (required).</param>
        /// <param name="type">Field type: string, integer, number, boolean, array (default to &quot;string&quot;).</param>
        /// <param name="required">Whether the field is required (default to false).</param>
        /// <param name="helpText">helpText.</param>
        /// <param name="spec">spec.</param>
        public TemplateField(string key = default, string label = default, string type = @"string", bool required = false, string helpText = default, List<TemplateFieldSpec> spec = default)
        {
            // to ensure "key" is required (not null)
            if (key == null)
            {
                throw new ArgumentNullException("key is a required property for TemplateField and cannot be null");
            }
            this.Key = key;
            // to ensure "label" is required (not null)
            if (label == null)
            {
                throw new ArgumentNullException("label is a required property for TemplateField and cannot be null");
            }
            this.Label = label;
            // use default value if no "type" provided
            this.Type = type ?? @"string";
            this.Required = required;
            this.HelpText = helpText;
            this.Spec = spec;
        }

        /// <summary>
        /// Field key/identifier
        /// </summary>
        /// <value>Field key/identifier</value>
        [DataMember(Name = "key", IsRequired = true, EmitDefaultValue = true)]
        public string Key { get; set; }

        /// <summary>
        /// Human-readable label
        /// </summary>
        /// <value>Human-readable label</value>
        [DataMember(Name = "label", IsRequired = true, EmitDefaultValue = true)]
        public string Label { get; set; }

        /// <summary>
        /// Field type: string, integer, number, boolean, array
        /// </summary>
        /// <value>Field type: string, integer, number, boolean, array</value>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public string Type { get; set; }

        /// <summary>
        /// Whether the field is required
        /// </summary>
        /// <value>Whether the field is required</value>
        [DataMember(Name = "required", EmitDefaultValue = true)]
        public bool Required { get; set; }

        /// <summary>
        /// Gets or Sets HelpText
        /// </summary>
        [DataMember(Name = "helpText", EmitDefaultValue = true)]
        public string HelpText { get; set; }

        /// <summary>
        /// Gets or Sets Spec
        /// </summary>
        [DataMember(Name = "spec", EmitDefaultValue = true)]
        public List<TemplateFieldSpec> Spec { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TemplateField {\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  Label: ").Append(Label).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Required: ").Append(Required).Append("\n");
            sb.Append("  HelpText: ").Append(HelpText).Append("\n");
            sb.Append("  Spec: ").Append(Spec).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
