/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.1.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TemplateFox.SDK.Client.FileParameter;
using OpenAPIDateConverter = TemplateFox.SDK.Client.OpenAPIDateConverter;

namespace TemplateFox.SDK.Model
{
    /// <summary>
    /// Transaction record
    /// </summary>
    [DataContract(Name = "Transaction")]
    public partial class Transaction : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Transaction" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Transaction() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Transaction" /> class.
        /// </summary>
        /// <param name="transactionRef">Unique transaction reference (UUID) (required).</param>
        /// <param name="transactionType">Transaction type: PDFGEN, PURCHASE, REFUND, BONUS (required).</param>
        /// <param name="templateId">templateId.</param>
        /// <param name="execTm">execTm.</param>
        /// <param name="credits">Credits consumed (positive) or added (negative) (required).</param>
        /// <param name="createdAt">ISO 8601 timestamp (required).</param>
        public Transaction(string transactionRef = default, string transactionType = default, string templateId = default, int? execTm = default, int credits = default, string createdAt = default)
        {
            // to ensure "transactionRef" is required (not null)
            if (transactionRef == null)
            {
                throw new ArgumentNullException("transactionRef is a required property for Transaction and cannot be null");
            }
            this.TransactionRef = transactionRef;
            // to ensure "transactionType" is required (not null)
            if (transactionType == null)
            {
                throw new ArgumentNullException("transactionType is a required property for Transaction and cannot be null");
            }
            this.TransactionType = transactionType;
            this.Credits = credits;
            // to ensure "createdAt" is required (not null)
            if (createdAt == null)
            {
                throw new ArgumentNullException("createdAt is a required property for Transaction and cannot be null");
            }
            this.CreatedAt = createdAt;
            this.TemplateId = templateId;
            this.ExecTm = execTm;
        }

        /// <summary>
        /// Unique transaction reference (UUID)
        /// </summary>
        /// <value>Unique transaction reference (UUID)</value>
        [DataMember(Name = "transaction_ref", IsRequired = true, EmitDefaultValue = true)]
        public string TransactionRef { get; set; }

        /// <summary>
        /// Transaction type: PDFGEN, PURCHASE, REFUND, BONUS
        /// </summary>
        /// <value>Transaction type: PDFGEN, PURCHASE, REFUND, BONUS</value>
        [DataMember(Name = "transaction_type", IsRequired = true, EmitDefaultValue = true)]
        public string TransactionType { get; set; }

        /// <summary>
        /// Gets or Sets TemplateId
        /// </summary>
        [DataMember(Name = "template_id", EmitDefaultValue = true)]
        public string TemplateId { get; set; }

        /// <summary>
        /// Gets or Sets ExecTm
        /// </summary>
        [DataMember(Name = "exec_tm", EmitDefaultValue = true)]
        public int? ExecTm { get; set; }

        /// <summary>
        /// Credits consumed (positive) or added (negative)
        /// </summary>
        /// <value>Credits consumed (positive) or added (negative)</value>
        [DataMember(Name = "credits", IsRequired = true, EmitDefaultValue = true)]
        public int Credits { get; set; }

        /// <summary>
        /// ISO 8601 timestamp
        /// </summary>
        /// <value>ISO 8601 timestamp</value>
        [DataMember(Name = "created_at", IsRequired = true, EmitDefaultValue = true)]
        public string CreatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Transaction {\n");
            sb.Append("  TransactionRef: ").Append(TransactionRef).Append("\n");
            sb.Append("  TransactionType: ").Append(TransactionType).Append("\n");
            sb.Append("  TemplateId: ").Append(TemplateId).Append("\n");
            sb.Append("  ExecTm: ").Append(ExecTm).Append("\n");
            sb.Append("  Credits: ").Append(Credits).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
