/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.1.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TemplateFox.SDK.Client.FileParameter;
using OpenAPIDateConverter = TemplateFox.SDK.Client.OpenAPIDateConverter;

namespace TemplateFox.SDK.Model
{
    /// <summary>
    /// Response for transactions list endpoint
    /// </summary>
    [DataContract(Name = "TransactionsResponse")]
    public partial class TransactionsResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionsResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TransactionsResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionsResponse" /> class.
        /// </summary>
        /// <param name="transactions">transactions (required).</param>
        /// <param name="total">Total number of transactions (required).</param>
        /// <param name="limit">Number of records returned (required).</param>
        /// <param name="offset">Number of records skipped (required).</param>
        public TransactionsResponse(List<Transaction> transactions = default, int total = default, int limit = default, int offset = default)
        {
            // to ensure "transactions" is required (not null)
            if (transactions == null)
            {
                throw new ArgumentNullException("transactions is a required property for TransactionsResponse and cannot be null");
            }
            this.Transactions = transactions;
            this.Total = total;
            this.Limit = limit;
            this.Offset = offset;
        }

        /// <summary>
        /// Gets or Sets Transactions
        /// </summary>
        [DataMember(Name = "transactions", IsRequired = true, EmitDefaultValue = true)]
        public List<Transaction> Transactions { get; set; }

        /// <summary>
        /// Total number of transactions
        /// </summary>
        /// <value>Total number of transactions</value>
        [DataMember(Name = "total", IsRequired = true, EmitDefaultValue = true)]
        public int Total { get; set; }

        /// <summary>
        /// Number of records returned
        /// </summary>
        /// <value>Number of records returned</value>
        [DataMember(Name = "limit", IsRequired = true, EmitDefaultValue = true)]
        public int Limit { get; set; }

        /// <summary>
        /// Number of records skipped
        /// </summary>
        /// <value>Number of records skipped</value>
        [DataMember(Name = "offset", IsRequired = true, EmitDefaultValue = true)]
        public int Offset { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TransactionsResponse {\n");
            sb.Append("  Transactions: ").Append(Transactions).Append("\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("  Limit: ").Append(Limit).Append("\n");
            sb.Append("  Offset: ").Append(Offset).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
