/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TemplateFox.SDK.Model;
using TemplateFox.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TemplateFox.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing AccountInfoResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccountInfoResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AccountInfoResponse
        //private AccountInfoResponse instance;

        public AccountInfoResponseTests()
        {
            // TODO uncomment below to create an instance of AccountInfoResponse
            //instance = new AccountInfoResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccountInfoResponse
        /// </summary>
        [Fact]
        public void AccountInfoResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AccountInfoResponse
            //Assert.IsType<AccountInfoResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Credits'
        /// </summary>
        [Fact]
        public void CreditsTest()
        {
            // TODO unit test for the property 'Credits'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
    }
}
