/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.5.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TemplateFox.SDK.Model;
using TemplateFox.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TemplateFox.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing CreateAsyncPdfResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateAsyncPdfResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateAsyncPdfResponse
        //private CreateAsyncPdfResponse instance;

        public CreateAsyncPdfResponseTests()
        {
            // TODO uncomment below to create an instance of CreateAsyncPdfResponse
            //instance = new CreateAsyncPdfResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateAsyncPdfResponse
        /// </summary>
        [Fact]
        public void CreateAsyncPdfResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateAsyncPdfResponse
            //Assert.IsType<CreateAsyncPdfResponse>(instance);
        }

        /// <summary>
        /// Test the property 'JobId'
        /// </summary>
        [Fact]
        public void JobIdTest()
        {
            // TODO unit test for the property 'JobId'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'CreditsRemaining'
        /// </summary>
        [Fact]
        public void CreditsRemainingTest()
        {
            // TODO unit test for the property 'CreditsRemaining'
        }
    }
}
