/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.6.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TemplateFox.SDK.Model;
using TemplateFox.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TemplateFox.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing CreateAsyncPdfRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateAsyncPdfRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateAsyncPdfRequest
        //private CreateAsyncPdfRequest instance;

        public CreateAsyncPdfRequestTests()
        {
            // TODO uncomment below to create an instance of CreateAsyncPdfRequest
            //instance = new CreateAsyncPdfRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateAsyncPdfRequest
        /// </summary>
        [Fact]
        public void CreateAsyncPdfRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateAsyncPdfRequest
            //Assert.IsType<CreateAsyncPdfRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TemplateId'
        /// </summary>
        [Fact]
        public void TemplateIdTest()
        {
            // TODO unit test for the property 'TemplateId'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'ExportType'
        /// </summary>
        [Fact]
        public void ExportTypeTest()
        {
            // TODO unit test for the property 'ExportType'
        }

        /// <summary>
        /// Test the property 'Expiration'
        /// </summary>
        [Fact]
        public void ExpirationTest()
        {
            // TODO unit test for the property 'Expiration'
        }

        /// <summary>
        /// Test the property 'Filename'
        /// </summary>
        [Fact]
        public void FilenameTest()
        {
            // TODO unit test for the property 'Filename'
        }

        /// <summary>
        /// Test the property 'StoreS3'
        /// </summary>
        [Fact]
        public void StoreS3Test()
        {
            // TODO unit test for the property 'StoreS3'
        }

        /// <summary>
        /// Test the property 'S3Filepath'
        /// </summary>
        [Fact]
        public void S3FilepathTest()
        {
            // TODO unit test for the property 'S3Filepath'
        }

        /// <summary>
        /// Test the property 'S3Bucket'
        /// </summary>
        [Fact]
        public void S3BucketTest()
        {
            // TODO unit test for the property 'S3Bucket'
        }

        /// <summary>
        /// Test the property 'WebhookUrl'
        /// </summary>
        [Fact]
        public void WebhookUrlTest()
        {
            // TODO unit test for the property 'WebhookUrl'
        }

        /// <summary>
        /// Test the property 'WebhookSecret'
        /// </summary>
        [Fact]
        public void WebhookSecretTest()
        {
            // TODO unit test for the property 'WebhookSecret'
        }
    }
}
