/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.6.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TemplateFox.SDK.Model;
using TemplateFox.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TemplateFox.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing JobListResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JobListResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JobListResponse
        //private JobListResponse instance;

        public JobListResponseTests()
        {
            // TODO uncomment below to create an instance of JobListResponse
            //instance = new JobListResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JobListResponse
        /// </summary>
        [Fact]
        public void JobListResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" JobListResponse
            //Assert.IsType<JobListResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Jobs'
        /// </summary>
        [Fact]
        public void JobsTest()
        {
            // TODO unit test for the property 'Jobs'
        }

        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }

        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Fact]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }

        /// <summary>
        /// Test the property 'Offset'
        /// </summary>
        [Fact]
        public void OffsetTest()
        {
            // TODO unit test for the property 'Offset'
        }
    }
}
