/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.5.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TemplateFox.SDK.Model;
using TemplateFox.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TemplateFox.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing JobStatusResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JobStatusResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JobStatusResponse
        //private JobStatusResponse instance;

        public JobStatusResponseTests()
        {
            // TODO uncomment below to create an instance of JobStatusResponse
            //instance = new JobStatusResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JobStatusResponse
        /// </summary>
        [Fact]
        public void JobStatusResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" JobStatusResponse
            //Assert.IsType<JobStatusResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'TemplateId'
        /// </summary>
        [Fact]
        public void TemplateIdTest()
        {
            // TODO unit test for the property 'TemplateId'
        }

        /// <summary>
        /// Test the property 'ExportType'
        /// </summary>
        [Fact]
        public void ExportTypeTest()
        {
            // TODO unit test for the property 'ExportType'
        }

        /// <summary>
        /// Test the property 'Filename'
        /// </summary>
        [Fact]
        public void FilenameTest()
        {
            // TODO unit test for the property 'Filename'
        }

        /// <summary>
        /// Test the property 'StoreS3'
        /// </summary>
        [Fact]
        public void StoreS3Test()
        {
            // TODO unit test for the property 'StoreS3'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'CompletedAt'
        /// </summary>
        [Fact]
        public void CompletedAtTest()
        {
            // TODO unit test for the property 'CompletedAt'
        }

        /// <summary>
        /// Test the property 'ResultUrl'
        /// </summary>
        [Fact]
        public void ResultUrlTest()
        {
            // TODO unit test for the property 'ResultUrl'
        }

        /// <summary>
        /// Test the property 'ResultFilename'
        /// </summary>
        [Fact]
        public void ResultFilenameTest()
        {
            // TODO unit test for the property 'ResultFilename'
        }

        /// <summary>
        /// Test the property 'ResultExpiresAt'
        /// </summary>
        [Fact]
        public void ResultExpiresAtTest()
        {
            // TODO unit test for the property 'ResultExpiresAt'
        }

        /// <summary>
        /// Test the property 'ResultS3Bucket'
        /// </summary>
        [Fact]
        public void ResultS3BucketTest()
        {
            // TODO unit test for the property 'ResultS3Bucket'
        }

        /// <summary>
        /// Test the property 'ResultS3Key'
        /// </summary>
        [Fact]
        public void ResultS3KeyTest()
        {
            // TODO unit test for the property 'ResultS3Key'
        }

        /// <summary>
        /// Test the property 'ErrorMessage'
        /// </summary>
        [Fact]
        public void ErrorMessageTest()
        {
            // TODO unit test for the property 'ErrorMessage'
        }

        /// <summary>
        /// Test the property 'ErrorCode'
        /// </summary>
        [Fact]
        public void ErrorCodeTest()
        {
            // TODO unit test for the property 'ErrorCode'
        }
    }
}
