/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TemplateFox.SDK.Model;
using TemplateFox.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TemplateFox.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing S3ConfigResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class S3ConfigResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for S3ConfigResponse
        //private S3ConfigResponse instance;

        public S3ConfigResponseTests()
        {
            // TODO uncomment below to create an instance of S3ConfigResponse
            //instance = new S3ConfigResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of S3ConfigResponse
        /// </summary>
        [Fact]
        public void S3ConfigResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" S3ConfigResponse
            //Assert.IsType<S3ConfigResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Configured'
        /// </summary>
        [Fact]
        public void ConfiguredTest()
        {
            // TODO unit test for the property 'Configured'
        }

        /// <summary>
        /// Test the property 'EndpointUrl'
        /// </summary>
        [Fact]
        public void EndpointUrlTest()
        {
            // TODO unit test for the property 'EndpointUrl'
        }

        /// <summary>
        /// Test the property 'AccessKeyId'
        /// </summary>
        [Fact]
        public void AccessKeyIdTest()
        {
            // TODO unit test for the property 'AccessKeyId'
        }

        /// <summary>
        /// Test the property 'SecretAccessKeyMasked'
        /// </summary>
        [Fact]
        public void SecretAccessKeyMaskedTest()
        {
            // TODO unit test for the property 'SecretAccessKeyMasked'
        }

        /// <summary>
        /// Test the property 'BucketName'
        /// </summary>
        [Fact]
        public void BucketNameTest()
        {
            // TODO unit test for the property 'BucketName'
        }

        /// <summary>
        /// Test the property 'DefaultPrefix'
        /// </summary>
        [Fact]
        public void DefaultPrefixTest()
        {
            // TODO unit test for the property 'DefaultPrefix'
        }
    }
}
