/*
 * TemplateFox API
 *
 * Generate PDFs from HTML templates via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TemplateFox.SDK.Model;
using TemplateFox.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TemplateFox.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing S3ConfigRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class S3ConfigRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for S3ConfigRequest
        //private S3ConfigRequest instance;

        public S3ConfigRequestTests()
        {
            // TODO uncomment below to create an instance of S3ConfigRequest
            //instance = new S3ConfigRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of S3ConfigRequest
        /// </summary>
        [Fact]
        public void S3ConfigRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" S3ConfigRequest
            //Assert.IsType<S3ConfigRequest>(instance);
        }

        /// <summary>
        /// Test the property 'EndpointUrl'
        /// </summary>
        [Fact]
        public void EndpointUrlTest()
        {
            // TODO unit test for the property 'EndpointUrl'
        }

        /// <summary>
        /// Test the property 'AccessKeyId'
        /// </summary>
        [Fact]
        public void AccessKeyIdTest()
        {
            // TODO unit test for the property 'AccessKeyId'
        }

        /// <summary>
        /// Test the property 'SecretAccessKey'
        /// </summary>
        [Fact]
        public void SecretAccessKeyTest()
        {
            // TODO unit test for the property 'SecretAccessKey'
        }

        /// <summary>
        /// Test the property 'BucketName'
        /// </summary>
        [Fact]
        public void BucketNameTest()
        {
            // TODO unit test for the property 'BucketName'
        }

        /// <summary>
        /// Test the property 'DefaultPrefix'
        /// </summary>
        [Fact]
        public void DefaultPrefixTest()
        {
            // TODO unit test for the property 'DefaultPrefix'
        }
    }
}
