/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.5.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TemplateFox.SDK.Model;
using TemplateFox.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TemplateFox.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing S3SuccessResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class S3SuccessResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for S3SuccessResponse
        //private S3SuccessResponse instance;

        public S3SuccessResponseTests()
        {
            // TODO uncomment below to create an instance of S3SuccessResponse
            //instance = new S3SuccessResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of S3SuccessResponse
        /// </summary>
        [Fact]
        public void S3SuccessResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" S3SuccessResponse
            //Assert.IsType<S3SuccessResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }
    }
}
