/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TemplateFox.SDK.Model;
using TemplateFox.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TemplateFox.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing TemplateField
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TemplateFieldTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TemplateField
        //private TemplateField instance;

        public TemplateFieldTests()
        {
            // TODO uncomment below to create an instance of TemplateField
            //instance = new TemplateField();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TemplateField
        /// </summary>
        [Fact]
        public void TemplateFieldInstanceTest()
        {
            // TODO uncomment below to test "IsType" TemplateField
            //Assert.IsType<TemplateField>(instance);
        }

        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }

        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Fact]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Required'
        /// </summary>
        [Fact]
        public void RequiredTest()
        {
            // TODO unit test for the property 'Required'
        }

        /// <summary>
        /// Test the property 'HelpText'
        /// </summary>
        [Fact]
        public void HelpTextTest()
        {
            // TODO unit test for the property 'HelpText'
        }

        /// <summary>
        /// Test the property 'Spec'
        /// </summary>
        [Fact]
        public void SpecTest()
        {
            // TODO unit test for the property 'Spec'
        }
    }
}
