/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TemplateFox.SDK.Model;
using TemplateFox.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TemplateFox.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing TemplatesListResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TemplatesListResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TemplatesListResponse
        //private TemplatesListResponse instance;

        public TemplatesListResponseTests()
        {
            // TODO uncomment below to create an instance of TemplatesListResponse
            //instance = new TemplatesListResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TemplatesListResponse
        /// </summary>
        [Fact]
        public void TemplatesListResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" TemplatesListResponse
            //Assert.IsType<TemplatesListResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Templates'
        /// </summary>
        [Fact]
        public void TemplatesTest()
        {
            // TODO unit test for the property 'Templates'
        }
    }
}
