/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.4.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TemplateFox.SDK.Model;
using TemplateFox.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TemplateFox.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing TransactionsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransactionsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TransactionsResponse
        //private TransactionsResponse instance;

        public TransactionsResponseTests()
        {
            // TODO uncomment below to create an instance of TransactionsResponse
            //instance = new TransactionsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TransactionsResponse
        /// </summary>
        [Fact]
        public void TransactionsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" TransactionsResponse
            //Assert.IsType<TransactionsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Transactions'
        /// </summary>
        [Fact]
        public void TransactionsTest()
        {
            // TODO unit test for the property 'Transactions'
        }

        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }

        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Fact]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }

        /// <summary>
        /// Test the property 'Offset'
        /// </summary>
        [Fact]
        public void OffsetTest()
        {
            // TODO unit test for the property 'Offset'
        }
    }
}
