/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.4.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using TemplateFox.SDK.Client;
using TemplateFox.SDK.Model;

namespace TemplateFox.SDK.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAccountApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get account info
        /// </summary>
        /// <remarks>
        /// Get account information including remaining credits.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header) or JWT token  **Usage:** Check credit balance before performing operations.  **No credits consumed:** This is a read-only endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>AccountInfoResponse</returns>
        AccountInfoResponse GetAccount();

        /// <summary>
        /// Get account info
        /// </summary>
        /// <remarks>
        /// Get account information including remaining credits.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header) or JWT token  **Usage:** Check credit balance before performing operations.  **No credits consumed:** This is a read-only endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of AccountInfoResponse</returns>
        ApiResponse<AccountInfoResponse> GetAccountWithHttpInfo();
        /// <summary>
        /// List transactions
        /// </summary>
        /// <remarks>
        /// List transaction history for the authenticated user.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header) or JWT token  **Pagination:** Use &#x60;limit&#x60; and &#x60;offset&#x60; query parameters.  **Transaction types:** - &#x60;PDFGEN&#x60;: PDF generation (consumes credits) - &#x60;REFUND&#x60;: Credit refund (on failed generation) - &#x60;PURCHASE&#x60;: Credit purchase - &#x60;BONUS&#x60;: Bonus credits  **Credits field:** - Positive value &#x3D; credits consumed - Negative value &#x3D; credits added  **No credits consumed:** This is a read-only endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Number of records to return (optional, default to 300)</param>
        /// <param name="offset">Number of records to skip (optional, default to 0)</param>
        /// <returns>TransactionsResponse</returns>
        TransactionsResponse ListTransactions(int? limit = default, int? offset = default);

        /// <summary>
        /// List transactions
        /// </summary>
        /// <remarks>
        /// List transaction history for the authenticated user.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header) or JWT token  **Pagination:** Use &#x60;limit&#x60; and &#x60;offset&#x60; query parameters.  **Transaction types:** - &#x60;PDFGEN&#x60;: PDF generation (consumes credits) - &#x60;REFUND&#x60;: Credit refund (on failed generation) - &#x60;PURCHASE&#x60;: Credit purchase - &#x60;BONUS&#x60;: Bonus credits  **Credits field:** - Positive value &#x3D; credits consumed - Negative value &#x3D; credits added  **No credits consumed:** This is a read-only endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Number of records to return (optional, default to 300)</param>
        /// <param name="offset">Number of records to skip (optional, default to 0)</param>
        /// <returns>ApiResponse of TransactionsResponse</returns>
        ApiResponse<TransactionsResponse> ListTransactionsWithHttpInfo(int? limit = default, int? offset = default);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAccountApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get account info
        /// </summary>
        /// <remarks>
        /// Get account information including remaining credits.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header) or JWT token  **Usage:** Check credit balance before performing operations.  **No credits consumed:** This is a read-only endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AccountInfoResponse</returns>
        System.Threading.Tasks.Task<AccountInfoResponse> GetAccountAsync(System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get account info
        /// </summary>
        /// <remarks>
        /// Get account information including remaining credits.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header) or JWT token  **Usage:** Check credit balance before performing operations.  **No credits consumed:** This is a read-only endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AccountInfoResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<AccountInfoResponse>> GetAccountWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// List transactions
        /// </summary>
        /// <remarks>
        /// List transaction history for the authenticated user.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header) or JWT token  **Pagination:** Use &#x60;limit&#x60; and &#x60;offset&#x60; query parameters.  **Transaction types:** - &#x60;PDFGEN&#x60;: PDF generation (consumes credits) - &#x60;REFUND&#x60;: Credit refund (on failed generation) - &#x60;PURCHASE&#x60;: Credit purchase - &#x60;BONUS&#x60;: Bonus credits  **Credits field:** - Positive value &#x3D; credits consumed - Negative value &#x3D; credits added  **No credits consumed:** This is a read-only endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Number of records to return (optional, default to 300)</param>
        /// <param name="offset">Number of records to skip (optional, default to 0)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TransactionsResponse</returns>
        System.Threading.Tasks.Task<TransactionsResponse> ListTransactionsAsync(int? limit = default, int? offset = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// List transactions
        /// </summary>
        /// <remarks>
        /// List transaction history for the authenticated user.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header) or JWT token  **Pagination:** Use &#x60;limit&#x60; and &#x60;offset&#x60; query parameters.  **Transaction types:** - &#x60;PDFGEN&#x60;: PDF generation (consumes credits) - &#x60;REFUND&#x60;: Credit refund (on failed generation) - &#x60;PURCHASE&#x60;: Credit purchase - &#x60;BONUS&#x60;: Bonus credits  **Credits field:** - Positive value &#x3D; credits consumed - Negative value &#x3D; credits added  **No credits consumed:** This is a read-only endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Number of records to return (optional, default to 300)</param>
        /// <param name="offset">Number of records to skip (optional, default to 0)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TransactionsResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<TransactionsResponse>> ListTransactionsWithHttpInfoAsync(int? limit = default, int? offset = default, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAccountApi : IAccountApiSync, IAccountApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class AccountApi : IDisposable, IAccountApi
    {
        private TemplateFox.SDK.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public AccountApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public AccountApi(string basePath)
        {
            this.Configuration = TemplateFox.SDK.Client.Configuration.MergeConfigurations(
                TemplateFox.SDK.Client.GlobalConfiguration.Instance,
                new TemplateFox.SDK.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new TemplateFox.SDK.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = TemplateFox.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public AccountApi(TemplateFox.SDK.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = TemplateFox.SDK.Client.Configuration.MergeConfigurations(
                TemplateFox.SDK.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new TemplateFox.SDK.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = TemplateFox.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public AccountApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public AccountApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = TemplateFox.SDK.Client.Configuration.MergeConfigurations(
                TemplateFox.SDK.Client.GlobalConfiguration.Instance,
                new TemplateFox.SDK.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new TemplateFox.SDK.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = TemplateFox.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public AccountApi(HttpClient client, TemplateFox.SDK.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = TemplateFox.SDK.Client.Configuration.MergeConfigurations(
                TemplateFox.SDK.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new TemplateFox.SDK.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = TemplateFox.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public AccountApi(TemplateFox.SDK.Client.ISynchronousClient client, TemplateFox.SDK.Client.IAsynchronousClient asyncClient, TemplateFox.SDK.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = TemplateFox.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public TemplateFox.SDK.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public TemplateFox.SDK.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public TemplateFox.SDK.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public TemplateFox.SDK.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public TemplateFox.SDK.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get account info Get account information including remaining credits.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header) or JWT token  **Usage:** Check credit balance before performing operations.  **No credits consumed:** This is a read-only endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>AccountInfoResponse</returns>
        public AccountInfoResponse GetAccount()
        {
            TemplateFox.SDK.Client.ApiResponse<AccountInfoResponse> localVarResponse = GetAccountWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get account info Get account information including remaining credits.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header) or JWT token  **Usage:** Check credit balance before performing operations.  **No credits consumed:** This is a read-only endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of AccountInfoResponse</returns>
        public TemplateFox.SDK.Client.ApiResponse<AccountInfoResponse> GetAccountWithHttpInfo()
        {
            TemplateFox.SDK.Client.RequestOptions localVarRequestOptions = new TemplateFox.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = TemplateFox.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = TemplateFox.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<AccountInfoResponse>("/v1/account", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAccount", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get account info Get account information including remaining credits.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header) or JWT token  **Usage:** Check credit balance before performing operations.  **No credits consumed:** This is a read-only endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AccountInfoResponse</returns>
        public async System.Threading.Tasks.Task<AccountInfoResponse> GetAccountAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            TemplateFox.SDK.Client.ApiResponse<AccountInfoResponse> localVarResponse = await GetAccountWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get account info Get account information including remaining credits.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header) or JWT token  **Usage:** Check credit balance before performing operations.  **No credits consumed:** This is a read-only endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AccountInfoResponse)</returns>
        public async System.Threading.Tasks.Task<TemplateFox.SDK.Client.ApiResponse<AccountInfoResponse>> GetAccountWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default)
        {

            TemplateFox.SDK.Client.RequestOptions localVarRequestOptions = new TemplateFox.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = TemplateFox.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = TemplateFox.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<AccountInfoResponse>("/v1/account", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAccount", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List transactions List transaction history for the authenticated user.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header) or JWT token  **Pagination:** Use &#x60;limit&#x60; and &#x60;offset&#x60; query parameters.  **Transaction types:** - &#x60;PDFGEN&#x60;: PDF generation (consumes credits) - &#x60;REFUND&#x60;: Credit refund (on failed generation) - &#x60;PURCHASE&#x60;: Credit purchase - &#x60;BONUS&#x60;: Bonus credits  **Credits field:** - Positive value &#x3D; credits consumed - Negative value &#x3D; credits added  **No credits consumed:** This is a read-only endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Number of records to return (optional, default to 300)</param>
        /// <param name="offset">Number of records to skip (optional, default to 0)</param>
        /// <returns>TransactionsResponse</returns>
        public TransactionsResponse ListTransactions(int? limit = default, int? offset = default)
        {
            TemplateFox.SDK.Client.ApiResponse<TransactionsResponse> localVarResponse = ListTransactionsWithHttpInfo(limit, offset);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List transactions List transaction history for the authenticated user.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header) or JWT token  **Pagination:** Use &#x60;limit&#x60; and &#x60;offset&#x60; query parameters.  **Transaction types:** - &#x60;PDFGEN&#x60;: PDF generation (consumes credits) - &#x60;REFUND&#x60;: Credit refund (on failed generation) - &#x60;PURCHASE&#x60;: Credit purchase - &#x60;BONUS&#x60;: Bonus credits  **Credits field:** - Positive value &#x3D; credits consumed - Negative value &#x3D; credits added  **No credits consumed:** This is a read-only endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Number of records to return (optional, default to 300)</param>
        /// <param name="offset">Number of records to skip (optional, default to 0)</param>
        /// <returns>ApiResponse of TransactionsResponse</returns>
        public TemplateFox.SDK.Client.ApiResponse<TransactionsResponse> ListTransactionsWithHttpInfo(int? limit = default, int? offset = default)
        {
            TemplateFox.SDK.Client.RequestOptions localVarRequestOptions = new TemplateFox.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = TemplateFox.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = TemplateFox.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(TemplateFox.SDK.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (offset != null)
            {
                localVarRequestOptions.QueryParameters.Add(TemplateFox.SDK.Client.ClientUtils.ParameterToMultiMap("", "offset", offset));
            }

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<TransactionsResponse>("/v1/account/transactions", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListTransactions", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List transactions List transaction history for the authenticated user.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header) or JWT token  **Pagination:** Use &#x60;limit&#x60; and &#x60;offset&#x60; query parameters.  **Transaction types:** - &#x60;PDFGEN&#x60;: PDF generation (consumes credits) - &#x60;REFUND&#x60;: Credit refund (on failed generation) - &#x60;PURCHASE&#x60;: Credit purchase - &#x60;BONUS&#x60;: Bonus credits  **Credits field:** - Positive value &#x3D; credits consumed - Negative value &#x3D; credits added  **No credits consumed:** This is a read-only endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Number of records to return (optional, default to 300)</param>
        /// <param name="offset">Number of records to skip (optional, default to 0)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TransactionsResponse</returns>
        public async System.Threading.Tasks.Task<TransactionsResponse> ListTransactionsAsync(int? limit = default, int? offset = default, System.Threading.CancellationToken cancellationToken = default)
        {
            TemplateFox.SDK.Client.ApiResponse<TransactionsResponse> localVarResponse = await ListTransactionsWithHttpInfoAsync(limit, offset, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List transactions List transaction history for the authenticated user.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header) or JWT token  **Pagination:** Use &#x60;limit&#x60; and &#x60;offset&#x60; query parameters.  **Transaction types:** - &#x60;PDFGEN&#x60;: PDF generation (consumes credits) - &#x60;REFUND&#x60;: Credit refund (on failed generation) - &#x60;PURCHASE&#x60;: Credit purchase - &#x60;BONUS&#x60;: Bonus credits  **Credits field:** - Positive value &#x3D; credits consumed - Negative value &#x3D; credits added  **No credits consumed:** This is a read-only endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Number of records to return (optional, default to 300)</param>
        /// <param name="offset">Number of records to skip (optional, default to 0)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TransactionsResponse)</returns>
        public async System.Threading.Tasks.Task<TemplateFox.SDK.Client.ApiResponse<TransactionsResponse>> ListTransactionsWithHttpInfoAsync(int? limit = default, int? offset = default, System.Threading.CancellationToken cancellationToken = default)
        {

            TemplateFox.SDK.Client.RequestOptions localVarRequestOptions = new TemplateFox.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = TemplateFox.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = TemplateFox.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(TemplateFox.SDK.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (offset != null)
            {
                localVarRequestOptions.QueryParameters.Add(TemplateFox.SDK.Client.ClientUtils.ParameterToMultiMap("", "offset", offset));
            }

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<TransactionsResponse>("/v1/account/transactions", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListTransactions", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
