/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using TemplateFox.SDK.Client;
using TemplateFox.SDK.Model;

namespace TemplateFox.SDK.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IIntegrationsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Delete S3 configuration
        /// </summary>
        /// <remarks>
        /// Delete S3 storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Remove your S3 integration. Generated PDFs will use the default CDN storage after deletion.  **Warning:** This action is irreversible. You&#39;ll need to reconfigure S3 to use it again.  **No credits consumed:** This is a configuration endpoint.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>S3SuccessResponse</returns>
        S3SuccessResponse DeleteS3Config();

        /// <summary>
        /// Delete S3 configuration
        /// </summary>
        /// <remarks>
        /// Delete S3 storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Remove your S3 integration. Generated PDFs will use the default CDN storage after deletion.  **Warning:** This action is irreversible. You&#39;ll need to reconfigure S3 to use it again.  **No credits consumed:** This is a configuration endpoint.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of S3SuccessResponse</returns>
        ApiResponse<S3SuccessResponse> DeleteS3ConfigWithHttpInfo();
        /// <summary>
        /// Get S3 configuration
        /// </summary>
        /// <remarks>
        /// Get current S3 storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Retrieve your S3 integration settings. Secret access key is masked for security.  **Returns 404** if S3 is not configured.  **No credits consumed:** This is a read-only endpoint.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>S3ConfigResponse</returns>
        S3ConfigResponse GetS3Config();

        /// <summary>
        /// Get S3 configuration
        /// </summary>
        /// <remarks>
        /// Get current S3 storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Retrieve your S3 integration settings. Secret access key is masked for security.  **Returns 404** if S3 is not configured.  **No credits consumed:** This is a read-only endpoint.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of S3ConfigResponse</returns>
        ApiResponse<S3ConfigResponse> GetS3ConfigWithHttpInfo();
        /// <summary>
        /// Save S3 configuration
        /// </summary>
        /// <remarks>
        /// Save or update S3-compatible storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Configure your S3-compatible storage to receive generated PDFs directly in your own bucket instead of the default CDN.  **Supported providers:** - Amazon S3 - DigitalOcean Spaces - Cloudflare R2 - MinIO - Any S3-compatible storage  **Secret key behavior:** - For new configuration: &#x60;secret_access_key&#x60; is required - For updates: Omit &#x60;secret_access_key&#x60; to keep existing value  **No credits consumed:** This is a configuration endpoint.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="s3ConfigRequest"></param>
        /// <returns>S3SuccessResponse</returns>
        S3SuccessResponse SaveS3Config(S3ConfigRequest s3ConfigRequest);

        /// <summary>
        /// Save S3 configuration
        /// </summary>
        /// <remarks>
        /// Save or update S3-compatible storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Configure your S3-compatible storage to receive generated PDFs directly in your own bucket instead of the default CDN.  **Supported providers:** - Amazon S3 - DigitalOcean Spaces - Cloudflare R2 - MinIO - Any S3-compatible storage  **Secret key behavior:** - For new configuration: &#x60;secret_access_key&#x60; is required - For updates: Omit &#x60;secret_access_key&#x60; to keep existing value  **No credits consumed:** This is a configuration endpoint.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="s3ConfigRequest"></param>
        /// <returns>ApiResponse of S3SuccessResponse</returns>
        ApiResponse<S3SuccessResponse> SaveS3ConfigWithHttpInfo(S3ConfigRequest s3ConfigRequest);
        /// <summary>
        /// Test S3 connection
        /// </summary>
        /// <remarks>
        /// Test S3 connection with stored credentials.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Verify your S3 configuration is working correctly. The test will: 1. Connect to the endpoint 2. Verify bucket access 3. Check write permissions by uploading a small test file  **Prerequisite:** S3 must be configured first using &#x60;POST /v1/integrations/s3&#x60;  **No credits consumed:** This is a diagnostic endpoint.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>S3TestResponse</returns>
        S3TestResponse TestS3Connection();

        /// <summary>
        /// Test S3 connection
        /// </summary>
        /// <remarks>
        /// Test S3 connection with stored credentials.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Verify your S3 configuration is working correctly. The test will: 1. Connect to the endpoint 2. Verify bucket access 3. Check write permissions by uploading a small test file  **Prerequisite:** S3 must be configured first using &#x60;POST /v1/integrations/s3&#x60;  **No credits consumed:** This is a diagnostic endpoint.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of S3TestResponse</returns>
        ApiResponse<S3TestResponse> TestS3ConnectionWithHttpInfo();
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IIntegrationsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Delete S3 configuration
        /// </summary>
        /// <remarks>
        /// Delete S3 storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Remove your S3 integration. Generated PDFs will use the default CDN storage after deletion.  **Warning:** This action is irreversible. You&#39;ll need to reconfigure S3 to use it again.  **No credits consumed:** This is a configuration endpoint.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of S3SuccessResponse</returns>
        System.Threading.Tasks.Task<S3SuccessResponse> DeleteS3ConfigAsync(System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Delete S3 configuration
        /// </summary>
        /// <remarks>
        /// Delete S3 storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Remove your S3 integration. Generated PDFs will use the default CDN storage after deletion.  **Warning:** This action is irreversible. You&#39;ll need to reconfigure S3 to use it again.  **No credits consumed:** This is a configuration endpoint.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (S3SuccessResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<S3SuccessResponse>> DeleteS3ConfigWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Get S3 configuration
        /// </summary>
        /// <remarks>
        /// Get current S3 storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Retrieve your S3 integration settings. Secret access key is masked for security.  **Returns 404** if S3 is not configured.  **No credits consumed:** This is a read-only endpoint.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of S3ConfigResponse</returns>
        System.Threading.Tasks.Task<S3ConfigResponse> GetS3ConfigAsync(System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get S3 configuration
        /// </summary>
        /// <remarks>
        /// Get current S3 storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Retrieve your S3 integration settings. Secret access key is masked for security.  **Returns 404** if S3 is not configured.  **No credits consumed:** This is a read-only endpoint.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (S3ConfigResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<S3ConfigResponse>> GetS3ConfigWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Save S3 configuration
        /// </summary>
        /// <remarks>
        /// Save or update S3-compatible storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Configure your S3-compatible storage to receive generated PDFs directly in your own bucket instead of the default CDN.  **Supported providers:** - Amazon S3 - DigitalOcean Spaces - Cloudflare R2 - MinIO - Any S3-compatible storage  **Secret key behavior:** - For new configuration: &#x60;secret_access_key&#x60; is required - For updates: Omit &#x60;secret_access_key&#x60; to keep existing value  **No credits consumed:** This is a configuration endpoint.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="s3ConfigRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of S3SuccessResponse</returns>
        System.Threading.Tasks.Task<S3SuccessResponse> SaveS3ConfigAsync(S3ConfigRequest s3ConfigRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Save S3 configuration
        /// </summary>
        /// <remarks>
        /// Save or update S3-compatible storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Configure your S3-compatible storage to receive generated PDFs directly in your own bucket instead of the default CDN.  **Supported providers:** - Amazon S3 - DigitalOcean Spaces - Cloudflare R2 - MinIO - Any S3-compatible storage  **Secret key behavior:** - For new configuration: &#x60;secret_access_key&#x60; is required - For updates: Omit &#x60;secret_access_key&#x60; to keep existing value  **No credits consumed:** This is a configuration endpoint.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="s3ConfigRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (S3SuccessResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<S3SuccessResponse>> SaveS3ConfigWithHttpInfoAsync(S3ConfigRequest s3ConfigRequest, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Test S3 connection
        /// </summary>
        /// <remarks>
        /// Test S3 connection with stored credentials.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Verify your S3 configuration is working correctly. The test will: 1. Connect to the endpoint 2. Verify bucket access 3. Check write permissions by uploading a small test file  **Prerequisite:** S3 must be configured first using &#x60;POST /v1/integrations/s3&#x60;  **No credits consumed:** This is a diagnostic endpoint.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of S3TestResponse</returns>
        System.Threading.Tasks.Task<S3TestResponse> TestS3ConnectionAsync(System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Test S3 connection
        /// </summary>
        /// <remarks>
        /// Test S3 connection with stored credentials.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Verify your S3 configuration is working correctly. The test will: 1. Connect to the endpoint 2. Verify bucket access 3. Check write permissions by uploading a small test file  **Prerequisite:** S3 must be configured first using &#x60;POST /v1/integrations/s3&#x60;  **No credits consumed:** This is a diagnostic endpoint.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (S3TestResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<S3TestResponse>> TestS3ConnectionWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IIntegrationsApi : IIntegrationsApiSync, IIntegrationsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class IntegrationsApi : IDisposable, IIntegrationsApi
    {
        private TemplateFox.SDK.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="IntegrationsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public IntegrationsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="IntegrationsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public IntegrationsApi(string basePath)
        {
            this.Configuration = TemplateFox.SDK.Client.Configuration.MergeConfigurations(
                TemplateFox.SDK.Client.GlobalConfiguration.Instance,
                new TemplateFox.SDK.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new TemplateFox.SDK.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = TemplateFox.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="IntegrationsApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public IntegrationsApi(TemplateFox.SDK.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = TemplateFox.SDK.Client.Configuration.MergeConfigurations(
                TemplateFox.SDK.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new TemplateFox.SDK.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = TemplateFox.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="IntegrationsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public IntegrationsApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="IntegrationsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public IntegrationsApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = TemplateFox.SDK.Client.Configuration.MergeConfigurations(
                TemplateFox.SDK.Client.GlobalConfiguration.Instance,
                new TemplateFox.SDK.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new TemplateFox.SDK.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = TemplateFox.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="IntegrationsApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public IntegrationsApi(HttpClient client, TemplateFox.SDK.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = TemplateFox.SDK.Client.Configuration.MergeConfigurations(
                TemplateFox.SDK.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new TemplateFox.SDK.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = TemplateFox.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="IntegrationsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public IntegrationsApi(TemplateFox.SDK.Client.ISynchronousClient client, TemplateFox.SDK.Client.IAsynchronousClient asyncClient, TemplateFox.SDK.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = TemplateFox.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public TemplateFox.SDK.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public TemplateFox.SDK.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public TemplateFox.SDK.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public TemplateFox.SDK.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public TemplateFox.SDK.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Delete S3 configuration Delete S3 storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Remove your S3 integration. Generated PDFs will use the default CDN storage after deletion.  **Warning:** This action is irreversible. You&#39;ll need to reconfigure S3 to use it again.  **No credits consumed:** This is a configuration endpoint.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>S3SuccessResponse</returns>
        public S3SuccessResponse DeleteS3Config()
        {
            TemplateFox.SDK.Client.ApiResponse<S3SuccessResponse> localVarResponse = DeleteS3ConfigWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete S3 configuration Delete S3 storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Remove your S3 integration. Generated PDFs will use the default CDN storage after deletion.  **Warning:** This action is irreversible. You&#39;ll need to reconfigure S3 to use it again.  **No credits consumed:** This is a configuration endpoint.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of S3SuccessResponse</returns>
        public TemplateFox.SDK.Client.ApiResponse<S3SuccessResponse> DeleteS3ConfigWithHttpInfo()
        {
            TemplateFox.SDK.Client.RequestOptions localVarRequestOptions = new TemplateFox.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = TemplateFox.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = TemplateFox.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<S3SuccessResponse>("/v1/integrations/s3", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteS3Config", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete S3 configuration Delete S3 storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Remove your S3 integration. Generated PDFs will use the default CDN storage after deletion.  **Warning:** This action is irreversible. You&#39;ll need to reconfigure S3 to use it again.  **No credits consumed:** This is a configuration endpoint.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of S3SuccessResponse</returns>
        public async System.Threading.Tasks.Task<S3SuccessResponse> DeleteS3ConfigAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            TemplateFox.SDK.Client.ApiResponse<S3SuccessResponse> localVarResponse = await DeleteS3ConfigWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete S3 configuration Delete S3 storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Remove your S3 integration. Generated PDFs will use the default CDN storage after deletion.  **Warning:** This action is irreversible. You&#39;ll need to reconfigure S3 to use it again.  **No credits consumed:** This is a configuration endpoint.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (S3SuccessResponse)</returns>
        public async System.Threading.Tasks.Task<TemplateFox.SDK.Client.ApiResponse<S3SuccessResponse>> DeleteS3ConfigWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default)
        {

            TemplateFox.SDK.Client.RequestOptions localVarRequestOptions = new TemplateFox.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = TemplateFox.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = TemplateFox.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<S3SuccessResponse>("/v1/integrations/s3", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteS3Config", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get S3 configuration Get current S3 storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Retrieve your S3 integration settings. Secret access key is masked for security.  **Returns 404** if S3 is not configured.  **No credits consumed:** This is a read-only endpoint.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>S3ConfigResponse</returns>
        public S3ConfigResponse GetS3Config()
        {
            TemplateFox.SDK.Client.ApiResponse<S3ConfigResponse> localVarResponse = GetS3ConfigWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get S3 configuration Get current S3 storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Retrieve your S3 integration settings. Secret access key is masked for security.  **Returns 404** if S3 is not configured.  **No credits consumed:** This is a read-only endpoint.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of S3ConfigResponse</returns>
        public TemplateFox.SDK.Client.ApiResponse<S3ConfigResponse> GetS3ConfigWithHttpInfo()
        {
            TemplateFox.SDK.Client.RequestOptions localVarRequestOptions = new TemplateFox.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = TemplateFox.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = TemplateFox.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<S3ConfigResponse>("/v1/integrations/s3", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetS3Config", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get S3 configuration Get current S3 storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Retrieve your S3 integration settings. Secret access key is masked for security.  **Returns 404** if S3 is not configured.  **No credits consumed:** This is a read-only endpoint.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of S3ConfigResponse</returns>
        public async System.Threading.Tasks.Task<S3ConfigResponse> GetS3ConfigAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            TemplateFox.SDK.Client.ApiResponse<S3ConfigResponse> localVarResponse = await GetS3ConfigWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get S3 configuration Get current S3 storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Retrieve your S3 integration settings. Secret access key is masked for security.  **Returns 404** if S3 is not configured.  **No credits consumed:** This is a read-only endpoint.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (S3ConfigResponse)</returns>
        public async System.Threading.Tasks.Task<TemplateFox.SDK.Client.ApiResponse<S3ConfigResponse>> GetS3ConfigWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default)
        {

            TemplateFox.SDK.Client.RequestOptions localVarRequestOptions = new TemplateFox.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = TemplateFox.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = TemplateFox.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<S3ConfigResponse>("/v1/integrations/s3", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetS3Config", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Save S3 configuration Save or update S3-compatible storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Configure your S3-compatible storage to receive generated PDFs directly in your own bucket instead of the default CDN.  **Supported providers:** - Amazon S3 - DigitalOcean Spaces - Cloudflare R2 - MinIO - Any S3-compatible storage  **Secret key behavior:** - For new configuration: &#x60;secret_access_key&#x60; is required - For updates: Omit &#x60;secret_access_key&#x60; to keep existing value  **No credits consumed:** This is a configuration endpoint.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="s3ConfigRequest"></param>
        /// <returns>S3SuccessResponse</returns>
        public S3SuccessResponse SaveS3Config(S3ConfigRequest s3ConfigRequest)
        {
            TemplateFox.SDK.Client.ApiResponse<S3SuccessResponse> localVarResponse = SaveS3ConfigWithHttpInfo(s3ConfigRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Save S3 configuration Save or update S3-compatible storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Configure your S3-compatible storage to receive generated PDFs directly in your own bucket instead of the default CDN.  **Supported providers:** - Amazon S3 - DigitalOcean Spaces - Cloudflare R2 - MinIO - Any S3-compatible storage  **Secret key behavior:** - For new configuration: &#x60;secret_access_key&#x60; is required - For updates: Omit &#x60;secret_access_key&#x60; to keep existing value  **No credits consumed:** This is a configuration endpoint.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="s3ConfigRequest"></param>
        /// <returns>ApiResponse of S3SuccessResponse</returns>
        public TemplateFox.SDK.Client.ApiResponse<S3SuccessResponse> SaveS3ConfigWithHttpInfo(S3ConfigRequest s3ConfigRequest)
        {
            // verify the required parameter 's3ConfigRequest' is set
            if (s3ConfigRequest == null)
                throw new TemplateFox.SDK.Client.ApiException(400, "Missing required parameter 's3ConfigRequest' when calling IntegrationsApi->SaveS3Config");

            TemplateFox.SDK.Client.RequestOptions localVarRequestOptions = new TemplateFox.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = TemplateFox.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = TemplateFox.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = s3ConfigRequest;

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<S3SuccessResponse>("/v1/integrations/s3", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SaveS3Config", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Save S3 configuration Save or update S3-compatible storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Configure your S3-compatible storage to receive generated PDFs directly in your own bucket instead of the default CDN.  **Supported providers:** - Amazon S3 - DigitalOcean Spaces - Cloudflare R2 - MinIO - Any S3-compatible storage  **Secret key behavior:** - For new configuration: &#x60;secret_access_key&#x60; is required - For updates: Omit &#x60;secret_access_key&#x60; to keep existing value  **No credits consumed:** This is a configuration endpoint.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="s3ConfigRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of S3SuccessResponse</returns>
        public async System.Threading.Tasks.Task<S3SuccessResponse> SaveS3ConfigAsync(S3ConfigRequest s3ConfigRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            TemplateFox.SDK.Client.ApiResponse<S3SuccessResponse> localVarResponse = await SaveS3ConfigWithHttpInfoAsync(s3ConfigRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Save S3 configuration Save or update S3-compatible storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Configure your S3-compatible storage to receive generated PDFs directly in your own bucket instead of the default CDN.  **Supported providers:** - Amazon S3 - DigitalOcean Spaces - Cloudflare R2 - MinIO - Any S3-compatible storage  **Secret key behavior:** - For new configuration: &#x60;secret_access_key&#x60; is required - For updates: Omit &#x60;secret_access_key&#x60; to keep existing value  **No credits consumed:** This is a configuration endpoint.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="s3ConfigRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (S3SuccessResponse)</returns>
        public async System.Threading.Tasks.Task<TemplateFox.SDK.Client.ApiResponse<S3SuccessResponse>> SaveS3ConfigWithHttpInfoAsync(S3ConfigRequest s3ConfigRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 's3ConfigRequest' is set
            if (s3ConfigRequest == null)
                throw new TemplateFox.SDK.Client.ApiException(400, "Missing required parameter 's3ConfigRequest' when calling IntegrationsApi->SaveS3Config");


            TemplateFox.SDK.Client.RequestOptions localVarRequestOptions = new TemplateFox.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = TemplateFox.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = TemplateFox.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = s3ConfigRequest;

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<S3SuccessResponse>("/v1/integrations/s3", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SaveS3Config", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Test S3 connection Test S3 connection with stored credentials.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Verify your S3 configuration is working correctly. The test will: 1. Connect to the endpoint 2. Verify bucket access 3. Check write permissions by uploading a small test file  **Prerequisite:** S3 must be configured first using &#x60;POST /v1/integrations/s3&#x60;  **No credits consumed:** This is a diagnostic endpoint.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>S3TestResponse</returns>
        public S3TestResponse TestS3Connection()
        {
            TemplateFox.SDK.Client.ApiResponse<S3TestResponse> localVarResponse = TestS3ConnectionWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Test S3 connection Test S3 connection with stored credentials.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Verify your S3 configuration is working correctly. The test will: 1. Connect to the endpoint 2. Verify bucket access 3. Check write permissions by uploading a small test file  **Prerequisite:** S3 must be configured first using &#x60;POST /v1/integrations/s3&#x60;  **No credits consumed:** This is a diagnostic endpoint.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of S3TestResponse</returns>
        public TemplateFox.SDK.Client.ApiResponse<S3TestResponse> TestS3ConnectionWithHttpInfo()
        {
            TemplateFox.SDK.Client.RequestOptions localVarRequestOptions = new TemplateFox.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = TemplateFox.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = TemplateFox.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<S3TestResponse>("/v1/integrations/s3/test", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("TestS3Connection", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Test S3 connection Test S3 connection with stored credentials.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Verify your S3 configuration is working correctly. The test will: 1. Connect to the endpoint 2. Verify bucket access 3. Check write permissions by uploading a small test file  **Prerequisite:** S3 must be configured first using &#x60;POST /v1/integrations/s3&#x60;  **No credits consumed:** This is a diagnostic endpoint.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of S3TestResponse</returns>
        public async System.Threading.Tasks.Task<S3TestResponse> TestS3ConnectionAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            TemplateFox.SDK.Client.ApiResponse<S3TestResponse> localVarResponse = await TestS3ConnectionWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Test S3 connection Test S3 connection with stored credentials.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Verify your S3 configuration is working correctly. The test will: 1. Connect to the endpoint 2. Verify bucket access 3. Check write permissions by uploading a small test file  **Prerequisite:** S3 must be configured first using &#x60;POST /v1/integrations/s3&#x60;  **No credits consumed:** This is a diagnostic endpoint.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (S3TestResponse)</returns>
        public async System.Threading.Tasks.Task<TemplateFox.SDK.Client.ApiResponse<S3TestResponse>> TestS3ConnectionWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default)
        {

            TemplateFox.SDK.Client.RequestOptions localVarRequestOptions = new TemplateFox.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = TemplateFox.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = TemplateFox.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<S3TestResponse>("/v1/integrations/s3/test", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("TestS3Connection", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
