/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using TemplateFox.SDK.Client;
using TemplateFox.SDK.Model;

namespace TemplateFox.SDK.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPDFAsyncApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Generate PDF asynchronously
        /// </summary>
        /// <remarks>
        /// Queue a PDF generation job for async processing.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## How It Works  1. Submit a job with template and data 2. Receive a &#x60;job_id&#x60; immediately 3. Poll &#x60;/v1/pdf/status/{job_id}&#x60; for completion 4. Optionally receive a webhook notification  ## When to Use Async  Use async generation when: - Processing large documents or batches - You can&#39;t wait for synchronous response - You want webhook notifications  ## Webhooks  If &#x60;webhook_url&#x60; is provided, we&#39;ll POST to it when the job completes or fails:  &#x60;&#x60;&#x60;json {     \&quot;event\&quot;: \&quot;pdf.completed\&quot;,     \&quot;job_id\&quot;: \&quot;...\&quot;,     \&quot;status\&quot;: \&quot;completed\&quot;,     \&quot;result\&quot;: {         \&quot;url\&quot;: \&quot;https://...\&quot;,         \&quot;filename\&quot;: \&quot;invoice.pdf\&quot;     } } &#x60;&#x60;&#x60;  Webhooks include HMAC-SHA256 signature in &#x60;X-TemplateFox-Signature&#x60; header if you provide a &#x60;webhook_secret&#x60;.  **Credits:** 1 credit deducted immediately (refunded if job fails permanently).
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAsyncPdfRequest"></param>
        /// <returns>CreateAsyncPdfResponse</returns>
        CreateAsyncPdfResponse CreatePdfAsync(CreateAsyncPdfRequest createAsyncPdfRequest);

        /// <summary>
        /// Generate PDF asynchronously
        /// </summary>
        /// <remarks>
        /// Queue a PDF generation job for async processing.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## How It Works  1. Submit a job with template and data 2. Receive a &#x60;job_id&#x60; immediately 3. Poll &#x60;/v1/pdf/status/{job_id}&#x60; for completion 4. Optionally receive a webhook notification  ## When to Use Async  Use async generation when: - Processing large documents or batches - You can&#39;t wait for synchronous response - You want webhook notifications  ## Webhooks  If &#x60;webhook_url&#x60; is provided, we&#39;ll POST to it when the job completes or fails:  &#x60;&#x60;&#x60;json {     \&quot;event\&quot;: \&quot;pdf.completed\&quot;,     \&quot;job_id\&quot;: \&quot;...\&quot;,     \&quot;status\&quot;: \&quot;completed\&quot;,     \&quot;result\&quot;: {         \&quot;url\&quot;: \&quot;https://...\&quot;,         \&quot;filename\&quot;: \&quot;invoice.pdf\&quot;     } } &#x60;&#x60;&#x60;  Webhooks include HMAC-SHA256 signature in &#x60;X-TemplateFox-Signature&#x60; header if you provide a &#x60;webhook_secret&#x60;.  **Credits:** 1 credit deducted immediately (refunded if job fails permanently).
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAsyncPdfRequest"></param>
        /// <returns>ApiResponse of CreateAsyncPdfResponse</returns>
        ApiResponse<CreateAsyncPdfResponse> CreatePdfAsyncWithHttpInfo(CreateAsyncPdfRequest createAsyncPdfRequest);
        /// <summary>
        /// Get PDF job status
        /// </summary>
        /// <remarks>
        /// Get the current status of an async PDF generation job.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Status Values  | Status | Description | |- -- -- -- -|- -- -- -- -- -- --| | &#x60;pending&#x60; | Job is queued, waiting to be processed | | &#x60;processing&#x60; | Job is being processed | | &#x60;completed&#x60; | PDF generated successfully | | &#x60;failed&#x60; | Job failed (check error_message) |  ## Polling Recommendations  - Poll every 1-2 seconds for small documents - Poll every 5-10 seconds for large documents - Consider using webhooks instead of polling
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobId"></param>
        /// <returns>JobStatusResponse</returns>
        JobStatusResponse GetPdfJob(string jobId);

        /// <summary>
        /// Get PDF job status
        /// </summary>
        /// <remarks>
        /// Get the current status of an async PDF generation job.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Status Values  | Status | Description | |- -- -- -- -|- -- -- -- -- -- --| | &#x60;pending&#x60; | Job is queued, waiting to be processed | | &#x60;processing&#x60; | Job is being processed | | &#x60;completed&#x60; | PDF generated successfully | | &#x60;failed&#x60; | Job failed (check error_message) |  ## Polling Recommendations  - Poll every 1-2 seconds for small documents - Poll every 5-10 seconds for large documents - Consider using webhooks instead of polling
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobId"></param>
        /// <returns>ApiResponse of JobStatusResponse</returns>
        ApiResponse<JobStatusResponse> GetPdfJobWithHttpInfo(string jobId);
        /// <summary>
        /// List PDF jobs
        /// </summary>
        /// <remarks>
        /// List async PDF generation jobs for your team.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  Supports pagination and filtering by status.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 20)</param>
        /// <param name="offset"> (optional, default to 0)</param>
        /// <param name="status"> (optional)</param>
        /// <returns>JobListResponse</returns>
        JobListResponse ListPdfJobs(int? limit = default, int? offset = default, JobStatus? status = default);

        /// <summary>
        /// List PDF jobs
        /// </summary>
        /// <remarks>
        /// List async PDF generation jobs for your team.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  Supports pagination and filtering by status.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 20)</param>
        /// <param name="offset"> (optional, default to 0)</param>
        /// <param name="status"> (optional)</param>
        /// <returns>ApiResponse of JobListResponse</returns>
        ApiResponse<JobListResponse> ListPdfJobsWithHttpInfo(int? limit = default, int? offset = default, JobStatus? status = default);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPDFAsyncApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Generate PDF asynchronously
        /// </summary>
        /// <remarks>
        /// Queue a PDF generation job for async processing.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## How It Works  1. Submit a job with template and data 2. Receive a &#x60;job_id&#x60; immediately 3. Poll &#x60;/v1/pdf/status/{job_id}&#x60; for completion 4. Optionally receive a webhook notification  ## When to Use Async  Use async generation when: - Processing large documents or batches - You can&#39;t wait for synchronous response - You want webhook notifications  ## Webhooks  If &#x60;webhook_url&#x60; is provided, we&#39;ll POST to it when the job completes or fails:  &#x60;&#x60;&#x60;json {     \&quot;event\&quot;: \&quot;pdf.completed\&quot;,     \&quot;job_id\&quot;: \&quot;...\&quot;,     \&quot;status\&quot;: \&quot;completed\&quot;,     \&quot;result\&quot;: {         \&quot;url\&quot;: \&quot;https://...\&quot;,         \&quot;filename\&quot;: \&quot;invoice.pdf\&quot;     } } &#x60;&#x60;&#x60;  Webhooks include HMAC-SHA256 signature in &#x60;X-TemplateFox-Signature&#x60; header if you provide a &#x60;webhook_secret&#x60;.  **Credits:** 1 credit deducted immediately (refunded if job fails permanently).
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAsyncPdfRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CreateAsyncPdfResponse</returns>
        System.Threading.Tasks.Task<CreateAsyncPdfResponse> CreatePdfAsyncAsync(CreateAsyncPdfRequest createAsyncPdfRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Generate PDF asynchronously
        /// </summary>
        /// <remarks>
        /// Queue a PDF generation job for async processing.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## How It Works  1. Submit a job with template and data 2. Receive a &#x60;job_id&#x60; immediately 3. Poll &#x60;/v1/pdf/status/{job_id}&#x60; for completion 4. Optionally receive a webhook notification  ## When to Use Async  Use async generation when: - Processing large documents or batches - You can&#39;t wait for synchronous response - You want webhook notifications  ## Webhooks  If &#x60;webhook_url&#x60; is provided, we&#39;ll POST to it when the job completes or fails:  &#x60;&#x60;&#x60;json {     \&quot;event\&quot;: \&quot;pdf.completed\&quot;,     \&quot;job_id\&quot;: \&quot;...\&quot;,     \&quot;status\&quot;: \&quot;completed\&quot;,     \&quot;result\&quot;: {         \&quot;url\&quot;: \&quot;https://...\&quot;,         \&quot;filename\&quot;: \&quot;invoice.pdf\&quot;     } } &#x60;&#x60;&#x60;  Webhooks include HMAC-SHA256 signature in &#x60;X-TemplateFox-Signature&#x60; header if you provide a &#x60;webhook_secret&#x60;.  **Credits:** 1 credit deducted immediately (refunded if job fails permanently).
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAsyncPdfRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CreateAsyncPdfResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<CreateAsyncPdfResponse>> CreatePdfAsyncWithHttpInfoAsync(CreateAsyncPdfRequest createAsyncPdfRequest, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Get PDF job status
        /// </summary>
        /// <remarks>
        /// Get the current status of an async PDF generation job.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Status Values  | Status | Description | |- -- -- -- -|- -- -- -- -- -- --| | &#x60;pending&#x60; | Job is queued, waiting to be processed | | &#x60;processing&#x60; | Job is being processed | | &#x60;completed&#x60; | PDF generated successfully | | &#x60;failed&#x60; | Job failed (check error_message) |  ## Polling Recommendations  - Poll every 1-2 seconds for small documents - Poll every 5-10 seconds for large documents - Consider using webhooks instead of polling
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of JobStatusResponse</returns>
        System.Threading.Tasks.Task<JobStatusResponse> GetPdfJobAsync(string jobId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get PDF job status
        /// </summary>
        /// <remarks>
        /// Get the current status of an async PDF generation job.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Status Values  | Status | Description | |- -- -- -- -|- -- -- -- -- -- --| | &#x60;pending&#x60; | Job is queued, waiting to be processed | | &#x60;processing&#x60; | Job is being processed | | &#x60;completed&#x60; | PDF generated successfully | | &#x60;failed&#x60; | Job failed (check error_message) |  ## Polling Recommendations  - Poll every 1-2 seconds for small documents - Poll every 5-10 seconds for large documents - Consider using webhooks instead of polling
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (JobStatusResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<JobStatusResponse>> GetPdfJobWithHttpInfoAsync(string jobId, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// List PDF jobs
        /// </summary>
        /// <remarks>
        /// List async PDF generation jobs for your team.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  Supports pagination and filtering by status.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 20)</param>
        /// <param name="offset"> (optional, default to 0)</param>
        /// <param name="status"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of JobListResponse</returns>
        System.Threading.Tasks.Task<JobListResponse> ListPdfJobsAsync(int? limit = default, int? offset = default, JobStatus? status = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// List PDF jobs
        /// </summary>
        /// <remarks>
        /// List async PDF generation jobs for your team.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  Supports pagination and filtering by status.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 20)</param>
        /// <param name="offset"> (optional, default to 0)</param>
        /// <param name="status"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (JobListResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<JobListResponse>> ListPdfJobsWithHttpInfoAsync(int? limit = default, int? offset = default, JobStatus? status = default, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPDFAsyncApi : IPDFAsyncApiSync, IPDFAsyncApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class PDFAsyncApi : IDisposable, IPDFAsyncApi
    {
        private TemplateFox.SDK.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="PDFAsyncApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public PDFAsyncApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PDFAsyncApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public PDFAsyncApi(string basePath)
        {
            this.Configuration = TemplateFox.SDK.Client.Configuration.MergeConfigurations(
                TemplateFox.SDK.Client.GlobalConfiguration.Instance,
                new TemplateFox.SDK.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new TemplateFox.SDK.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = TemplateFox.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PDFAsyncApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public PDFAsyncApi(TemplateFox.SDK.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = TemplateFox.SDK.Client.Configuration.MergeConfigurations(
                TemplateFox.SDK.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new TemplateFox.SDK.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = TemplateFox.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PDFAsyncApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public PDFAsyncApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PDFAsyncApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public PDFAsyncApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = TemplateFox.SDK.Client.Configuration.MergeConfigurations(
                TemplateFox.SDK.Client.GlobalConfiguration.Instance,
                new TemplateFox.SDK.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new TemplateFox.SDK.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = TemplateFox.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PDFAsyncApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public PDFAsyncApi(HttpClient client, TemplateFox.SDK.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = TemplateFox.SDK.Client.Configuration.MergeConfigurations(
                TemplateFox.SDK.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new TemplateFox.SDK.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = TemplateFox.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PDFAsyncApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public PDFAsyncApi(TemplateFox.SDK.Client.ISynchronousClient client, TemplateFox.SDK.Client.IAsynchronousClient asyncClient, TemplateFox.SDK.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = TemplateFox.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public TemplateFox.SDK.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public TemplateFox.SDK.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public TemplateFox.SDK.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public TemplateFox.SDK.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public TemplateFox.SDK.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Generate PDF asynchronously Queue a PDF generation job for async processing.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## How It Works  1. Submit a job with template and data 2. Receive a &#x60;job_id&#x60; immediately 3. Poll &#x60;/v1/pdf/status/{job_id}&#x60; for completion 4. Optionally receive a webhook notification  ## When to Use Async  Use async generation when: - Processing large documents or batches - You can&#39;t wait for synchronous response - You want webhook notifications  ## Webhooks  If &#x60;webhook_url&#x60; is provided, we&#39;ll POST to it when the job completes or fails:  &#x60;&#x60;&#x60;json {     \&quot;event\&quot;: \&quot;pdf.completed\&quot;,     \&quot;job_id\&quot;: \&quot;...\&quot;,     \&quot;status\&quot;: \&quot;completed\&quot;,     \&quot;result\&quot;: {         \&quot;url\&quot;: \&quot;https://...\&quot;,         \&quot;filename\&quot;: \&quot;invoice.pdf\&quot;     } } &#x60;&#x60;&#x60;  Webhooks include HMAC-SHA256 signature in &#x60;X-TemplateFox-Signature&#x60; header if you provide a &#x60;webhook_secret&#x60;.  **Credits:** 1 credit deducted immediately (refunded if job fails permanently).
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAsyncPdfRequest"></param>
        /// <returns>CreateAsyncPdfResponse</returns>
        public CreateAsyncPdfResponse CreatePdfAsync(CreateAsyncPdfRequest createAsyncPdfRequest)
        {
            TemplateFox.SDK.Client.ApiResponse<CreateAsyncPdfResponse> localVarResponse = CreatePdfAsyncWithHttpInfo(createAsyncPdfRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Generate PDF asynchronously Queue a PDF generation job for async processing.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## How It Works  1. Submit a job with template and data 2. Receive a &#x60;job_id&#x60; immediately 3. Poll &#x60;/v1/pdf/status/{job_id}&#x60; for completion 4. Optionally receive a webhook notification  ## When to Use Async  Use async generation when: - Processing large documents or batches - You can&#39;t wait for synchronous response - You want webhook notifications  ## Webhooks  If &#x60;webhook_url&#x60; is provided, we&#39;ll POST to it when the job completes or fails:  &#x60;&#x60;&#x60;json {     \&quot;event\&quot;: \&quot;pdf.completed\&quot;,     \&quot;job_id\&quot;: \&quot;...\&quot;,     \&quot;status\&quot;: \&quot;completed\&quot;,     \&quot;result\&quot;: {         \&quot;url\&quot;: \&quot;https://...\&quot;,         \&quot;filename\&quot;: \&quot;invoice.pdf\&quot;     } } &#x60;&#x60;&#x60;  Webhooks include HMAC-SHA256 signature in &#x60;X-TemplateFox-Signature&#x60; header if you provide a &#x60;webhook_secret&#x60;.  **Credits:** 1 credit deducted immediately (refunded if job fails permanently).
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAsyncPdfRequest"></param>
        /// <returns>ApiResponse of CreateAsyncPdfResponse</returns>
        public TemplateFox.SDK.Client.ApiResponse<CreateAsyncPdfResponse> CreatePdfAsyncWithHttpInfo(CreateAsyncPdfRequest createAsyncPdfRequest)
        {
            // verify the required parameter 'createAsyncPdfRequest' is set
            if (createAsyncPdfRequest == null)
                throw new TemplateFox.SDK.Client.ApiException(400, "Missing required parameter 'createAsyncPdfRequest' when calling PDFAsyncApi->CreatePdfAsync");

            TemplateFox.SDK.Client.RequestOptions localVarRequestOptions = new TemplateFox.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = TemplateFox.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = TemplateFox.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = createAsyncPdfRequest;

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<CreateAsyncPdfResponse>("/v1/pdf/create-async", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreatePdfAsync", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Generate PDF asynchronously Queue a PDF generation job for async processing.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## How It Works  1. Submit a job with template and data 2. Receive a &#x60;job_id&#x60; immediately 3. Poll &#x60;/v1/pdf/status/{job_id}&#x60; for completion 4. Optionally receive a webhook notification  ## When to Use Async  Use async generation when: - Processing large documents or batches - You can&#39;t wait for synchronous response - You want webhook notifications  ## Webhooks  If &#x60;webhook_url&#x60; is provided, we&#39;ll POST to it when the job completes or fails:  &#x60;&#x60;&#x60;json {     \&quot;event\&quot;: \&quot;pdf.completed\&quot;,     \&quot;job_id\&quot;: \&quot;...\&quot;,     \&quot;status\&quot;: \&quot;completed\&quot;,     \&quot;result\&quot;: {         \&quot;url\&quot;: \&quot;https://...\&quot;,         \&quot;filename\&quot;: \&quot;invoice.pdf\&quot;     } } &#x60;&#x60;&#x60;  Webhooks include HMAC-SHA256 signature in &#x60;X-TemplateFox-Signature&#x60; header if you provide a &#x60;webhook_secret&#x60;.  **Credits:** 1 credit deducted immediately (refunded if job fails permanently).
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAsyncPdfRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CreateAsyncPdfResponse</returns>
        public async System.Threading.Tasks.Task<CreateAsyncPdfResponse> CreatePdfAsyncAsync(CreateAsyncPdfRequest createAsyncPdfRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            TemplateFox.SDK.Client.ApiResponse<CreateAsyncPdfResponse> localVarResponse = await CreatePdfAsyncWithHttpInfoAsync(createAsyncPdfRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Generate PDF asynchronously Queue a PDF generation job for async processing.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## How It Works  1. Submit a job with template and data 2. Receive a &#x60;job_id&#x60; immediately 3. Poll &#x60;/v1/pdf/status/{job_id}&#x60; for completion 4. Optionally receive a webhook notification  ## When to Use Async  Use async generation when: - Processing large documents or batches - You can&#39;t wait for synchronous response - You want webhook notifications  ## Webhooks  If &#x60;webhook_url&#x60; is provided, we&#39;ll POST to it when the job completes or fails:  &#x60;&#x60;&#x60;json {     \&quot;event\&quot;: \&quot;pdf.completed\&quot;,     \&quot;job_id\&quot;: \&quot;...\&quot;,     \&quot;status\&quot;: \&quot;completed\&quot;,     \&quot;result\&quot;: {         \&quot;url\&quot;: \&quot;https://...\&quot;,         \&quot;filename\&quot;: \&quot;invoice.pdf\&quot;     } } &#x60;&#x60;&#x60;  Webhooks include HMAC-SHA256 signature in &#x60;X-TemplateFox-Signature&#x60; header if you provide a &#x60;webhook_secret&#x60;.  **Credits:** 1 credit deducted immediately (refunded if job fails permanently).
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAsyncPdfRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CreateAsyncPdfResponse)</returns>
        public async System.Threading.Tasks.Task<TemplateFox.SDK.Client.ApiResponse<CreateAsyncPdfResponse>> CreatePdfAsyncWithHttpInfoAsync(CreateAsyncPdfRequest createAsyncPdfRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'createAsyncPdfRequest' is set
            if (createAsyncPdfRequest == null)
                throw new TemplateFox.SDK.Client.ApiException(400, "Missing required parameter 'createAsyncPdfRequest' when calling PDFAsyncApi->CreatePdfAsync");


            TemplateFox.SDK.Client.RequestOptions localVarRequestOptions = new TemplateFox.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = TemplateFox.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = TemplateFox.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = createAsyncPdfRequest;

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<CreateAsyncPdfResponse>("/v1/pdf/create-async", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreatePdfAsync", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get PDF job status Get the current status of an async PDF generation job.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Status Values  | Status | Description | |- -- -- -- -|- -- -- -- -- -- --| | &#x60;pending&#x60; | Job is queued, waiting to be processed | | &#x60;processing&#x60; | Job is being processed | | &#x60;completed&#x60; | PDF generated successfully | | &#x60;failed&#x60; | Job failed (check error_message) |  ## Polling Recommendations  - Poll every 1-2 seconds for small documents - Poll every 5-10 seconds for large documents - Consider using webhooks instead of polling
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobId"></param>
        /// <returns>JobStatusResponse</returns>
        public JobStatusResponse GetPdfJob(string jobId)
        {
            TemplateFox.SDK.Client.ApiResponse<JobStatusResponse> localVarResponse = GetPdfJobWithHttpInfo(jobId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get PDF job status Get the current status of an async PDF generation job.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Status Values  | Status | Description | |- -- -- -- -|- -- -- -- -- -- --| | &#x60;pending&#x60; | Job is queued, waiting to be processed | | &#x60;processing&#x60; | Job is being processed | | &#x60;completed&#x60; | PDF generated successfully | | &#x60;failed&#x60; | Job failed (check error_message) |  ## Polling Recommendations  - Poll every 1-2 seconds for small documents - Poll every 5-10 seconds for large documents - Consider using webhooks instead of polling
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobId"></param>
        /// <returns>ApiResponse of JobStatusResponse</returns>
        public TemplateFox.SDK.Client.ApiResponse<JobStatusResponse> GetPdfJobWithHttpInfo(string jobId)
        {
            // verify the required parameter 'jobId' is set
            if (jobId == null)
                throw new TemplateFox.SDK.Client.ApiException(400, "Missing required parameter 'jobId' when calling PDFAsyncApi->GetPdfJob");

            TemplateFox.SDK.Client.RequestOptions localVarRequestOptions = new TemplateFox.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = TemplateFox.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = TemplateFox.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("job_id", TemplateFox.SDK.Client.ClientUtils.ParameterToString(jobId)); // path parameter

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<JobStatusResponse>("/v1/pdf/jobs/{job_id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetPdfJob", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get PDF job status Get the current status of an async PDF generation job.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Status Values  | Status | Description | |- -- -- -- -|- -- -- -- -- -- --| | &#x60;pending&#x60; | Job is queued, waiting to be processed | | &#x60;processing&#x60; | Job is being processed | | &#x60;completed&#x60; | PDF generated successfully | | &#x60;failed&#x60; | Job failed (check error_message) |  ## Polling Recommendations  - Poll every 1-2 seconds for small documents - Poll every 5-10 seconds for large documents - Consider using webhooks instead of polling
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of JobStatusResponse</returns>
        public async System.Threading.Tasks.Task<JobStatusResponse> GetPdfJobAsync(string jobId, System.Threading.CancellationToken cancellationToken = default)
        {
            TemplateFox.SDK.Client.ApiResponse<JobStatusResponse> localVarResponse = await GetPdfJobWithHttpInfoAsync(jobId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get PDF job status Get the current status of an async PDF generation job.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Status Values  | Status | Description | |- -- -- -- -|- -- -- -- -- -- --| | &#x60;pending&#x60; | Job is queued, waiting to be processed | | &#x60;processing&#x60; | Job is being processed | | &#x60;completed&#x60; | PDF generated successfully | | &#x60;failed&#x60; | Job failed (check error_message) |  ## Polling Recommendations  - Poll every 1-2 seconds for small documents - Poll every 5-10 seconds for large documents - Consider using webhooks instead of polling
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (JobStatusResponse)</returns>
        public async System.Threading.Tasks.Task<TemplateFox.SDK.Client.ApiResponse<JobStatusResponse>> GetPdfJobWithHttpInfoAsync(string jobId, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'jobId' is set
            if (jobId == null)
                throw new TemplateFox.SDK.Client.ApiException(400, "Missing required parameter 'jobId' when calling PDFAsyncApi->GetPdfJob");


            TemplateFox.SDK.Client.RequestOptions localVarRequestOptions = new TemplateFox.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = TemplateFox.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = TemplateFox.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("job_id", TemplateFox.SDK.Client.ClientUtils.ParameterToString(jobId)); // path parameter

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<JobStatusResponse>("/v1/pdf/jobs/{job_id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetPdfJob", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List PDF jobs List async PDF generation jobs for your team.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  Supports pagination and filtering by status.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 20)</param>
        /// <param name="offset"> (optional, default to 0)</param>
        /// <param name="status"> (optional)</param>
        /// <returns>JobListResponse</returns>
        public JobListResponse ListPdfJobs(int? limit = default, int? offset = default, JobStatus? status = default)
        {
            TemplateFox.SDK.Client.ApiResponse<JobListResponse> localVarResponse = ListPdfJobsWithHttpInfo(limit, offset, status);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List PDF jobs List async PDF generation jobs for your team.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  Supports pagination and filtering by status.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 20)</param>
        /// <param name="offset"> (optional, default to 0)</param>
        /// <param name="status"> (optional)</param>
        /// <returns>ApiResponse of JobListResponse</returns>
        public TemplateFox.SDK.Client.ApiResponse<JobListResponse> ListPdfJobsWithHttpInfo(int? limit = default, int? offset = default, JobStatus? status = default)
        {
            TemplateFox.SDK.Client.RequestOptions localVarRequestOptions = new TemplateFox.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = TemplateFox.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = TemplateFox.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(TemplateFox.SDK.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (offset != null)
            {
                localVarRequestOptions.QueryParameters.Add(TemplateFox.SDK.Client.ClientUtils.ParameterToMultiMap("", "offset", offset));
            }
            if (status != null)
            {
                localVarRequestOptions.QueryParameters.Add(TemplateFox.SDK.Client.ClientUtils.ParameterToMultiMap("", "status", status));
            }

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<JobListResponse>("/v1/pdf/jobs", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListPdfJobs", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List PDF jobs List async PDF generation jobs for your team.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  Supports pagination and filtering by status.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 20)</param>
        /// <param name="offset"> (optional, default to 0)</param>
        /// <param name="status"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of JobListResponse</returns>
        public async System.Threading.Tasks.Task<JobListResponse> ListPdfJobsAsync(int? limit = default, int? offset = default, JobStatus? status = default, System.Threading.CancellationToken cancellationToken = default)
        {
            TemplateFox.SDK.Client.ApiResponse<JobListResponse> localVarResponse = await ListPdfJobsWithHttpInfoAsync(limit, offset, status, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List PDF jobs List async PDF generation jobs for your team.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  Supports pagination and filtering by status.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 20)</param>
        /// <param name="offset"> (optional, default to 0)</param>
        /// <param name="status"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (JobListResponse)</returns>
        public async System.Threading.Tasks.Task<TemplateFox.SDK.Client.ApiResponse<JobListResponse>> ListPdfJobsWithHttpInfoAsync(int? limit = default, int? offset = default, JobStatus? status = default, System.Threading.CancellationToken cancellationToken = default)
        {

            TemplateFox.SDK.Client.RequestOptions localVarRequestOptions = new TemplateFox.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = TemplateFox.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = TemplateFox.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(TemplateFox.SDK.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (offset != null)
            {
                localVarRequestOptions.QueryParameters.Add(TemplateFox.SDK.Client.ClientUtils.ParameterToMultiMap("", "offset", offset));
            }
            if (status != null)
            {
                localVarRequestOptions.QueryParameters.Add(TemplateFox.SDK.Client.ClientUtils.ParameterToMultiMap("", "status", status));
            }

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<JobListResponse>("/v1/pdf/jobs", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListPdfJobs", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
